### ISSUE TITLE
Unable to get/set policies for access zone applications

### ISSUE THREAD

**Issue by ryan-dyer-sp** [cloudflare/python-cloudflare#100]
```
cli4  /zones/:domain/access/apps/:appid/policies
cli4: /zones/:domain/access/apps/:appid/policies - 12045 access.api.error.invalid_application_id
```
If I update api_v4.py to be 
```
self.add('AUTH', "zones", "access/apps", "policies")
```
instead of
```
self.add('AUTH', "zones", "access/apps/policies")
```
I can then get the policies for an app, but attempting to post results in:
```
cli4 --post name="Allow Okta Everyone" decision="allow" include='{ "okta": { "identity_provider_id": "<id>", "name": "Everyone" }}' /zones/:domain/access/apps/:appid/policies
cli4: /zones/:domain/access/apps/:appid/policies - 11020 access.api.error.failed_to_load_group
```

Am happy to submit PR if this change is all that is needed but not sure why the post operation isnt working.

Thanks,
Ryan

**Comment by mahtin** [comment]
You are correct - that is a type in `api_v4.py`. I will push a release to match https://api.cloudflare.com/#zone-level-access-policy-list-access-policies - stay tuned. A quick test with the code shows `GET` works:
```
$ cli4 /zones/::00000000000000000000000000000000/access/apps/::00000000-0000-0000-0000-000000000000/policies/::00000000-0000-0000-0000-000000000000
{
    "created_at": "2019-06-14T15:31:29Z",
    "decision": "allow",
    "exclude": [],
    "id": "00000000-0000-0000-0000-000000000000",
    "include": [
        {
            "email_domain": {
                "domain": "example.com"
            }
        }
    ],
    "name": "example",
    "precedence": 1,
    "require": [],
    "uid": "00000000-0000-0000-0000-000000000000",
    "updated_at": "2019-06-14T15:31:29Z"
}
$
```
However, like you, I can't get the ``--post`` to work. I think your command line is correct; but I need to ask for advice on this one. Stay tuned. More tomorrow.

**Comment by ryan-dyer-sp** [comment]
I found I was missing [] around the include map.  So I can now also post using the change mentioned.

Question in regards to using an api token.  What permissions do I need to provide this token in order to:
get/post:
  /zones/:id/access/apps
  /zones/:id/access/apps/:aid/policies

Thanks again.

**Comment by mahtin** [comment]
@ryan-dyer-sp - Ah! I missed that also. Sorry. As you realized, the `include`, `exclude`, and `require` values should be an array/list. As for your question; I would recommend you use the https://community.cloudflare.com/ site for that exact question. This issues areas is really for just the python libraries.

**Comment by mahtin** [comment]
The `2.8.9` release includes the initial issue you reported.
```
$ pip install -U cloudflare
...
Collecting cloudflare
...
    Found existing installation: cloudflare 2.8.6
    Uninstalling cloudflare-2.8.6:
      Successfully uninstalled cloudflare-2.8.6
Successfully installed cloudflare-2.8.9
$ 
```
