### ISSUE TITLE
add dependency from 'configparser'

### ISSUE THREAD

**Issue by random-user-879612354** [cloudflare/python-cloudflare#101]
python-cloudflare uses lib 'configparser', but there is no dependency warnings
(not in module, neither in documentation)
```
pip show cloudflare
Name: cloudflare
Version: 2.8.9
Summary: Python wrapper for the Cloudflare v4 API
Location: /usr/local/lib/python2.7/dist-packages

Requires: beautifulsoup4, jsonlines, pyyaml, requests
```

**Comment by mahtin** [comment]
Thank you for seeing this. It's been fixed. Please upgrade to `2.8.11` release via [pypi](https://pypi.org/project/cloudflare/) or equivalent. 
Also ... I see you are using Python2.x ... please upgrade to Python3.

**Comment by mnordhoff** [comment]
configparser (called ConfigParser in Python 2) is part of the standard library. It shouldn't need to be listed anywhere.

**Comment by mahtin** [comment]
2.8.12 released - @mnordhoff, you are correct and removed. Sorry for that sort-sited quick edit.

**Comment by mahtin** [comment]
2.8.13 release - clearly yesterday was a bad day to push releases quickly - I hiccuped a few times.
