### ISSUE TITLE
Firewall rules and filters to get the filter ID

### ISSUE THREAD

**Issue by tejav9981** [cloudflare/python-cloudflare#104]
Does it update the filter with ip list instead of ip address

data = {'mode': 'block', 'configuration': {'target': 'ip', 'value': 'ip_list'},'notes': 'Automatic block placed via Python script for IP_list : ' + str(ip_list)}..

Can you share example please

**Comment by mahtin** [comment]
According to the **User-level Firewall Access Rule** section of [api.cloudflare.com](https://api.cloudflare.com/#user-level-firewall-access-rule-list-access-rules) the `value` field should be:

> notes: IP is a single IPv4 address. IP range has a subnet of /16 or /24.

Hence you should pass a single IP address or IP block as a string and not a list.
