### ISSUE TITLE
Provide wheel

### ISSUE THREAD

**Issue by vsalvino** [cloudflare/python-cloudflare#108]
I'm wondering if there is any reason why wheels (.whl) are not being published in addition to the source distributions? One advantage to wheels from the python infrastructure standpoint is they install much faster as PyPI is able to pre-resolve the dependencies. And if your package is "pure" python (no C extensions) then building a wheel is very simple.

The command to build both source distribution and wheel is:
```
$ pip install wheel
$ python setup.py sdist bdist_wheel
```
Then upload both as usual to PyPI.

For more into see: https://pythonwheels.com/

**Comment by mahtin** [comment]
I'm happy to do this; however, I was under the impression that building/installing from scratch (vs via a wheel) was a safer thing to do regarding dependencies). That said, I'm happy do this. BTW: This isn't a big package; so I'm not sure it's going to save much time.

**Comment by vsalvino** [comment]
Awesome, thank you!

Wheel is the new standard as it sort of pre-resolves dependencies in setup.py at publish time, rather than at install time. So PyPI and pip then have knowledge of all this information without having to unpack and inspect the package at install time. This saves repetitive CPU and network activity that normally would have to happen on every machine every time the package is installed (think about millions of CI runners)

From the safety perspective, wheels are actually slightly more secure as no arbitrary code is run during install time. Versus with a source package, setup.py is run at install time (in theory setup.py could download a malware and run it in a subprocess, for example). However both formats can be signed and verified with hashes.

The other behavior of wheels is for C extensions (not relevant to cloudflare library, just FYI), is it pre-compiles the binaries for each OS and version of python. This is a huge convenience for users. But if you had a dependency on OpenSSL C extension, then you might choose not to publish a wheel to force the user to compile their own OpenSSL at install time, rather than using your pre-compiled binary.

**Comment by mahtin** [comment]
This is finally pushed to PyPI. Sorry to sat around for so long.
