### ISSUE TITLE
Spectrum Application Api

### ISSUE THREAD

**Issue by rock98rock** [cloudflare/python-cloudflare#110]
Hi may i know if the spectrum module is available? thank you

**Comment by mahtin** [comment]
Hello. The Spectrum API calls are in the code (please update if not).
```
$ cli4 --dump | egrep spectrum
/zones/:id/spectrum/analytics/aggregate/current
/zones/:id/spectrum/analytics/events/bytime
/zones/:id/spectrum/analytics/events/summary
/zones/:id/spectrum/apps
$
```
Hence, a Python call like `r = cf.zones.spectrum.apps.get(zone_id)` or a shell command like `cli4 /zones/:example.com/spectrum/apps` should work for you. Etc Etc. 

Note that some early Spectrum calls are now deprecated. See Cloudflare's support pages and [API page](https://api.cloudflare.com).
