### ISSUE TITLE
Read from CF_API_TOKEN?

### ISSUE THREAD

**Issue by jleclanche** [cloudflare/python-cloudflare#114]
Since API keys are deprecated, the `CF_API_TOKEN` naming would make more sense. It is also used by other libs ([example](https://github.com/go-acme/lego/pull/937/files)).

**Comment by mahtin** [comment]
This is somewhat correct and your logic is well founded. However, amazing as it is, these two packages are not designed to be in perfectly sync. (and yes, I realize exactly how that statement sounds. i.e strange!

As both packages are a good number of years old and both have a well established user base; I think this divergence is gonna stick.

**Comment by jleclanche** [comment]
Could support both pretty easily :) Anyway IMO I would rename it if only for the confusion and to avoid having people stuff API keys into something that expects API tokens.

**Comment by mahtin** [comment]
Yeah - yeah -yeah, it took a while. However, it's done. #114 is now pushed out in release #2.10.1

It's backward compatible (which was my number one issue). Updated README and the like.

Enjoy!
