### ISSUE TITLE
_call_network exception handler discards actual error

### ISSUE THREAD

**Issue by kpcyrd** [cloudflare/python-cloudflare#118]
I was troubleshooting a "connection failed." error that turned out to be a type issue (accidentally passed a dict instead of a string as api_token).

This is caught in a generic `except Exception`, but the actual exception is discarded in the exception handler and replaced with a simple "connection failed.", suggesting a network problem with no further info what might've happened.

https://github.com/cloudflare/python-cloudflare/blob/b70b5209664dc64ae4f0e5773806aec05b799cbd/CloudFlare/cloudflare.py#L202-L207

The only way to troubleshoot this is setting `debug=True` when creating the client and setting up logging to `DEBUG`:
```python
logging.basicConfig(level=logging.DEBUG)
cf = CloudFlare.CloudFlare(token=api_token, debug=True)
```

**Comment by mahtin** [comment]
Ah. I looked and you're correct; the code does in fact execute exceptions incorrectly. I've got a working solution and I'm testing it. It's the same as issue #113 and needs to be be fixed. Stay tuned.

**Comment by mahtin** [comment]
It release `2.16.0` the passed arguments to the `CloudFlare()` class creation are checked to confirm they are string types. While this does not address the overly-generic `Exception` handler in the code, it would stop this very understandable error from being masked. I will address that `Exception` handler later on as I agree, it has to go!

```python
        if email is not None and not isinstance(email, str):
            raise TypeError('email is %s - must be str' % (type(email)))
        if key is not None and not isinstance(key, str):
            raise TypeError('key is %s - must be str' % (type(key)))
        if token is not None and not isinstance(token, str):
            raise TypeError('token is %s - must be str' % (type(token)))
        if certtoken is not None and not isinstance(certtoken, str):
            raise TypeError('certtoken is %s - must be str' % (type(certtoken)))
```
