### ISSUE TITLE
Not coded yet: /zones/:example.com/logs/rayids/:{id}

### ISSUE THREAD

**Issue by alahijani** [cloudflare/python-cloudflare#119]
The following command doesn't seem to work:
```
cli4 /zones/:example.com/logs/rayids/:9999999999999999
```

but the corresponding curl command seems okay: 

```
curl -s \
  -H "Authorization: Bearer $CLOUDFLARE_API_TOKEN" \
  GET https://api.cloudflare.com/client/v4/zones/99999999999999999999999999999999/logs/rayids/9999999999999999
```

**Comment by mahtin** [comment]
Ah - so there's some very special processing done by the `cli4` command line program for values with a colon, i.e your `:9999999999999999` entry. A single `:` means interpret the value based on context. That's how the `:example.com` is converted to a numeric id value (it's the `/zones` before it that defines the context. However, there's no context coded up for the `/rayids` call.

However, the `cli4` program will allow double colon `::` to be used to pass raw values thru. Please try that. 

```
cli4 /zones/:example.com/logs/rayids/::9999999999999999
```

Please can you try your code again?

I'm sorry that was not clearly stated. I'll get this following edit into the code:

```bash
$ git diff cli4/cli4.man 
diff --git a/cli4/cli4.man b/cli4/cli4.man
index 8214f48..f539c47 100644
--- a/cli4/cli4.man
+++ b/cli4/cli4.man
@@ -72,6 +72,7 @@ The API command(s) to execute.
 .SH COMMAND(S)
 The command string uses slash (\fB/\fR) to seperate the verbs in the same way that the Cloudflare v4 API documentation does.
 Any verb starting with colon (\fB:\fR) is either converted to zone_id, user_id, organtization_id, or otherwise.
+Any verb starting with two colons (\fB::\fR) is passed thru raw.
 
 .SH RESULTS
 The output is either JSON or YAML formatted.
$
```

**Comment by alahijani** [comment]
The double colon `::` trick worked. Thank you!
