### ISSUE TITLE
Bring consistency in authentication between python-cloudflare and cf-terraforming (and other tools)

### ISSUE THREAD

**Issue by chris-zenfolio** [cloudflare/python-cloudflare#123]
The authentication methods for cf-terraforming rely on a yaml file, environment variables, command-line arguments, and/or a config file.

The cloudflare-python project has a different set of authentications, including different environment variables, a different config file and passing arguments when defining the class.

REQUEST: Please work with the cf-terraforming team to sync the authentication methods between the projects, preferably using the cloudflare-python method listed here: https://github.com/cloudflare/python-cloudflare#providing-cloudflare-username-and-api-key

The documentatin for how cf-terraforming authenticates is at https://github.com/cloudflare/cf-terraforming#authentication

This benefits everyone by having consistency and reduces the security risk by limiting the number of places passwords are stored on the filesystem.

Even if the cf-terraforming team chooses not to follow the cloudflare-python scheme, at least have the discussions so both projects (and any other projects) can benefit from a unified method of authentication.

A sister issue has been opened in cf-terraforming at https://github.com/cloudflare/cf-terraforming/issues/315

**Comment by mahtin** [comment]
I see that https://github.com/cloudflare/cf-terraforming/issues/315 is now closed. Note that as of release `2.9.7` (30 March, 2022) of this Python package, the environment variables `CLOUDFLARE_` are accepted (and preferred). The README was updated. Going forward, the `CLOUDFLARE_` environment variables are preferred.
