### ISSUE TITLE
Import API token from AWS secret manager

### ISSUE THREAD

**Issue by Doun72** [cloudflare/python-cloudflare#124]
I am using a Lambda function. I try to retrieve the API token from the AWS Secret Manager and I try to use it with the following commands:

secret = get_secret("Cloudflare_token")
cf = CloudFlare.CloudFlare(token=secret['TOKEN'])

I have the following error: CloudFlare.exceptions.CloudFlareAPIError: CloudFlare: configuration section missing
The secret is correctly retrieved from the Secret Manager.
Any idea?
Thanks in advance.

**Comment by Doun72** [comment]
I found the issue. I had to remove the cloudflare.cfg file from the folder ~/.cloudflare/. Now I have the following error with the command:
zones = cf.zones.get(params=params)

**CloudFlare.exceptions.CloudFlareAPIError: Invalid request headers**
Any idea?

**Comment by mahtin** [comment]
Please upgrade to the latest `2.9.8` via `pip install -U cloudflare` and you should be free of the `configuration section` error. As for the second issue ... run with debug=True and see if that helps explain. You should look at the examples folder for some `zones.get()` use of `params`.
