### ISSUE TITLE
CloudFlareAPIError: Authentication error - depending on token or key usage

### ISSUE THREAD

**Issue by kbroughton** [cloudflare/python-cloudflare#127]
$ cli4 --version
Cloudflare library version: 2.8.15

The Readme mentions that there are options for using API Tokens or API Keys to create a client. However, it fails to mention that some API calls REQUIRE the use of API key/email pair (not fine grained).  This should be made explicit and examples should be added. It's not fun to have to guess which client to use, and tab-completion suggests that any way you create the client would give you access to everything. 

Example: cf.accounts.audit_logs.get(identifier1=account_id, params=params)

If you call this with an API Token, even if it has privileges for account_logs, it will fail.

Demo:

```
account_id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
params={"since": "2021-01-01T00:00:00Z", 
        "before": "2021-12-30T00:00:00Z",
        "order": "when",
        "per_page": 1000,
        "direction": "desc",
        "page": 1}
api_token = 'get this from My Profile | Api Tokens | Top of page generates api Tokens'
cf_api_token_client = CloudFlare.CloudFlare(token=api_token)
cf_api_token_client.accounts.audit_logs.get(identifier1=account_id, params=params)

CloudFlareAPIError: Authentication
```

Now try with API Key

```
api_key = 'get this from My Profile | Api Tokens | Bottom of page generates api Keys'
cf_api_key_client = CloudFlare.CloudFlare(email=email, token=api_key)
cf_api_key_client.accounts.audit_logs.get(identifier1=account_id, params=params)
<lots of data>
Success!
```

Since your API is split between auth methods, I think it would be better if 
1. You unified auth on the backend
If that is not possible then
2. change the config file to allow (and encourage) token, key and email in one section
3. depending on the endpoint requested, select the appropriate client

**Comment by mahtin** [comment]
You are correct; however, the python library isn't the best place to code up these authentication methods. Well ... more-so than already exist in the code today.

That said, based on your description, I think you should open a ticket with Cloudflare as there's no reason why token authentication doesn't work. Try the support pages at https://support.cloudflare.com/

I'm going to close this here.

**Comment by kbroughton** [comment]
thanks, will do
