### ISSUE TITLE
[cli4] proxied=true is sending proxied=True

### ISSUE THREAD

**Issue by username-is-already-taken2** [cloudflare/python-cloudflare#130]
Hi there, I started using the cli4 program today, I was able to get my zones created fine (thanks very much) but I noticed an issue when I was importing my zone files.

Importing the file worked fine but I noticed if I provided the additional parameter for `proxied=true` the wrapper uppercases the True.  the [api](https://api.cloudflare.com/#dns-records-for-a-zone-import-dns-records) docs are expecting this in lowercase and wont respect `True` or at least method doesn't.  I tried `proxied='true'` `'proxied=true'` but when view the verbose output the finally curl command is always the same.

Hope have helps track down the issue

Gary

**Comment by mahtin** [comment]
The API is JSON and both upper and lower case are accepted (according to the spec). Here is a test from the `cli4` program ...
```
$ cli4 --post name=testing123.■■■■■■■■■■■■.com type=A content=223.0.0.1 proxied=True /zones/:■■■■■■■■■■■■.com/dns_records
{
    "content": "223.0.0.1",
    "created_on": "2022-01-29T10:36:27.304549Z",
    "id": "522eccbebb28ee75bacfce5e1a268b5b",
    "locked": false,
    "meta": {
        "auto_added": false,
        "managed_by_apps": false,
        "managed_by_argo_tunnel": false,
        "source": "primary"
    },
    "modified_on": "2022-01-29T10:36:27.304549Z",
    "name": "testing123.■■■■■■■■■■■■.com",
    "proxiable": true,
    "proxied": true,
    "ttl": 1,
    "type": "A",
    "zone_id": "acae16c92e8740474b94d5f35ccd11fe",
    "zone_name": "■■■■■■■■■■■■.com"
}
$

$ cli4 --delete /zones/:■■■■■■■■■■■■.com/dns_records/:testing123.■■■■■■■■■■■■.com
{
    "id": "522eccbebb28ee75bacfce5e1a268b5b"
}
$
```

I tried `true`, `True`, `false`, and `False`. All worked. In your example you have single quotes ... this does make a script easier to read; but does not change anything in the execution (as the shell removes the quotes before `cli4` is called.

I'm using ...

```
$ cli4 -V
Cloudflare library version: 2.8.15
$
```

... presently on a `macOS BigSur 11.2`. You can see the full version info via ...

```
$ cli4 -v /ips 2>&1 | egrep User-Agent
            -H "User-Agent: python-cloudflare/2.8.15/python-requests/2.25.1/python/3.8.2" \
$
```

So `Python 3.8.2` and `requests 2.25.1` in my case. I also upgraded `python-requests` to `2.27.1` and re-ran all this testing. It still worked.

BTW: You can also review all the JSON being sent in the API via the `-v` flag. Re-running the `--post`` from above and just grep'ing the important line shows this:

```
            --data '{'name': 'testing123.■■■■■■■■■■■■.com', 'type': 'A', 'content': '223.0.0.1', 'proxied': True}'
```
Notice that the code always uses the Capitalized version for the `proxied` value.

Hopefully this will help; however, please do provide an example if your code is still hiccuping. I'll leave this issue open.
