### ISSUE TITLE
1052 An error(-502) when cf.zones.post(data={'jump_start':False, 'name': zone_name})

### ISSUE THREAD

**Issue by Pheikrishvili** [cloudflare/python-cloudflare#131]
1052 An error(-502) occurs when running :
`cf.zones.post(data={'jump_start': False, 'name': zone_name, 'plan': plan, 'account': {'id': account}})`
Error is:
`"/zones.post - 1052 An error(-502) has occurred and it has been logged. We will fix this problem promptly. We apologize for the inconvenience - api call failed", "type": "log", "logger": "app.utilities.cloudflare_helper", "thread": "MainThread", "level": "ERROR", "module": "cloudflare_helper", "line_no": 178, "exc_info": "Traceback (most recent call last):\n  File \"/usr/src/app/app/utilities/cloudflare_helper.py\", line 172, in add_zone\n    'plan': plan, 'account': {'id': account}})\n  File \"/usr/local/lib/python3.6/site-packages/CloudFlare/cloudflare.py\", line 688, in post\n    params, data, files)\n  File \"/usr/local/lib/python3.6/site-packages/CloudFlare/cloudflare.py\", line 128, in call_with_auth\n    params, data, files)\n  File \"/usr/local/lib/python3.6/site-packages/CloudFlare/cloudflare.py\", line 502, in _call\n    raise CloudFlareAPIError(code, message)\nCloudFlare.exceptions.CloudFlareAPIError: An error(-502) has occurred and it has been logged. We will fix this problem promptly. We apologize for the inconvenience\n", "filename": "cloudflare_helper.py", "correlation_id": "fe87ba90-8259-11ec-9999-cade72529c41"`

**Comment by mahtin** [comment]
The error string "`An error(-502) has occurred and it has been logged. We will fix this problem promptly. We apologize for the inconvenience`" comes from the Cloudflare API interface. There's possibly no issue with your code or the `python-cloudflare` library. I would try this again later (or test it on the Cloudflare dashboard).

**Comment by Pheikrishvili** [comment]
> The error string "`An error(-502) has occurred and it has been logged. We will fix this problem promptly. We apologize for the inconvenience`" comes from the Cloudflare API interface. There's possibly no issue with your code or the `python-cloudflare` library. I would try this again later (or test it on the Cloudflare dashboard).

it was working about 2 weeks ago and no changes on my code side, I have tried different times from code but the error is same, from cloudflare interface everything is working fine, I have also opened a cloudflare support ticket and they suggested to open an issue here

**Comment by mahtin** [comment]
I fully understand. Sadly the error isn't within the Python library. It's in the backend within Cloudflare itself. See https://api.cloudflare.com/#zone-errors and scroll to `1052`. It reads `An error has occurred and it has been logged. We will fix this problem promptly. We apologize for the inconvenience`.

It's not you. It's not `python-cloudflare`. It's within Cloudflare itself.

**Comment by mahtin** [comment]
I just tested this via the command line code:

```
$ $ cli4 --post jump_start=False name="testing123.com" plan="Free" account="{'id': '...'}" /zones
...
    "id": "...",
    "name": "testing123.com",
    "status": "pending",
...
$

$ cli4 --delete /zones/:testing123.com
{
    "id": "..."
}
$
```

Please retry your code.
