### ISSUE TITLE
CloudFlare: configuration section missing

### ISSUE THREAD

**Issue by garyduong** [cloudflare/python-cloudflare#136]
I'd setup the API Token for Purge by URL, restricted by company Zone ID and have generated configuration file per https://github.com/cloudflare/python-cloudflare

However, when I test the cli4 utility on Amazon EC2 instance as superuser, I get the error.
```
# ls -a /root
.   ..   .cloudflare.cfg
# cli4 /zones/<zone-id>
CloudFlare: configuration section missing
# 
```
Configuration file
```
# cat /root/.cloudflare.cfg 
[Cloudflare]
token = <api-token>
# 
```

**Comment by mahtin** [comment]
In the README is has the example config file as:
```
[CloudFlare]
...
```

The capital "F" is subtle and easy to miss. You can change your config file right now to "F" and it will work. I'm going to push code to fix this and allow both types. Sorry for the confusion.

**Comment by garyduong** [comment]
It hasn't been fixed.
`# cat /root/.cloudflare.cfg 
[Cloudflare]
token = <redacted>
# cli4 --delete purge_everything=true /zones/<zone-id>/purge_cache
CloudFlare: configuration section missing
# `

**Comment by mahtin** [comment]
`2.9.8` is now pushed (with this fix)
