### ISSUE TITLE
Config broken in 2.9+

### ISSUE THREAD

**Issue by hyperknot** [cloudflare/python-cloudflare#137]
I've just started using this lib, however the config doesn't work and I don't even understand how it's supposed to work. On 2.8 everything is OK.

The problem is these lines, especially from this commit:
https://github.com/cloudflare/python-cloudflare/commit/7a0d715203b886f80b27f475ea8f35b25017613b

Most of these values are supposed to be None. Hence one of those lines will almost always trigger, thus this whole lib wouldn't load.

I'm talking about the official way of loading this lib:

```
    # An authenticated call using an API Token (note the missing email)
    cf = CloudFlare.CloudFlare(token='00000000000000000000000000000000')
    
    --> ValueError: email argument not string
```

```
 # An authenticated call using an API Key
    cf = CloudFlare.CloudFlare(email='user@example.com', token='00000000000000000000000000000000')

   --> ValueError: certtoken argument not string
```

This is the same with code or when loading from config file.

It's an easy fix, you just need to check if any of those are None as well, but I'm confused, how are people using this library?

**Comment by mahtin** [comment]
Yes - I'm sorry about that. The code uploaded earlier today has this error ... there was a case where a config file did not exist that would cause the error. This is fixed now in `2.9.7` and pushed to `pypi`. I will delete the release from earlier today.
