### ISSUE TITLE
Error message - argument of type 'instance' is not iterable

### ISSUE THREAD

**Issue by garyduong** [cloudflare/python-cloudflare#138]
It hasn't been fixed.
```
# cat /root/.cloudflare.cfg 
[Cloudflare]
token = <redacted>
# cli4 --delete purge_everything=true /zones/<zone-id>/purge_cache
CloudFlare: configuration section missing
#
```

_Originally posted by @garyduong in https://github.com/cloudflare/python-cloudflare/issues/136#issuecomment-1083823385_

**Comment by mahtin** [comment]
`2.9.8` is now pushed (with this fix)

**Comment by garyduong** [comment]
```
# cli4 --delete purge_everything=true /zones/<zone-id>/purge_cache
argument of type 'instance' is not iterable
# 
```

**Comment by mahtin** [comment]
Strange. I tried it and it's working cleanly (using my own domain vs `example.com`).

```
$ python -V
Python 3.8.7
$

$ cli4 -V
Cloudflare library version: 2.9.8
$

$ cli4 --delete purge_everything=true /zones/:example.com/purge_cache
{
    "id": "e23b18645c624c475b5f1a4a5edb5831"
}
$
```

Could you just confirm you've upgraded to `2.9.8` and/or maybe run with the `-v` command to work out where that error is coming from.

**Comment by garyduong** [comment]
Can you support Python 2.7.18 for the time being? We have some mission-critical APIs that rely on this legacy version.
```
# python -V
Python 2.7.18
# cli4 -V
Cloudflare library version: 2.9.8
# cli4 --delete purge_everything=true /zones/:example.com/purge_cache
argument of type 'instance' is not iterable
# 
```

**Comment by mahtin** [comment]
First off ... the official (python official) statement:

> DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained.

Now down to dealing with your real world issue. Legacy in the enterprise space (I assume this is a large company issue vs your home server). So I build up a `2.7.16` environment (I which was easier/quicker than going `2.7.18`). I think that will be ok for this work and I found the error. It's in how [ConfigParser](https://docs.python.org/3/library/configparser.html) can be coded in `2.x` vs modern day `3.x` Python. I have made it backwards compatible and hence the error you see will go away. This has no negative affect on folks running `3.x`. In fact ... the code is now cleaner to read. Go figure!

I have pushed `2.9.9` out to GitHub and PyPI. Please upgrade (`pip install -U cloudflare` or `pip2 install -U cloudflare` in your case).

Please report back.

**Comment by garyduong** [comment]
Thanks! Works fine now!
