### ISSUE TITLE
Does this wrapper allow me to use oAuth instead of API key or Access Token to access API on behalf of a cloudflare user?

### ISSUE THREAD

**Issue by simkimsia** [cloudflare/python-cloudflare#140]
As mentioned in #139, 

I am creating a SaaS that is already successfully integrated with DigitalOcean and GitHub API and my SaaS performs actions by 

1. allow user to connect their SaaS account with their DigitalOcean and GitHub accounts
2. and from there my SaaS now has the token from the oAuth login to call the DigitalOcean and GitHub APi respectively

Given taht CloudFlare appears to allow oAuth, can I use this python wrapper to call the API using the oAuth token rather than the CloudFlare users' API key or access token?

Just to make it clear, my SaaS is in Django hecne I am interested in this python wrapper

**Comment by mahtin** [comment]
Please read the [User API Tokens](https://api.cloudflare.com/#user-api-tokens-properties) section about tokens. There's no OAUTH within the API; however, setting up tokens is the method you want to use. This is fully covered on the [Developer API tokens and keys](https://developers.cloudflare.com/api/tokens/) site.


Once you are started down this path, here's a quick way to dump your created tokens. (Remove the `jq` etc part for the raw `JSON` part).
 
```
$ cli4 /user/tokens | jq -cr '.[]|.id,.issued_on,.modified_on,.last_used_on,.name' | paste - - - - - | sort -rk2,3 | column -t -s'	'
00000000000000000000000000000000  2021-04-04T16:52:04Z  2021-04-04T16:52:04Z  null                  Argo Tunnel API Token for ***
00000000000000000000000000000000  2020-11-24T19:41:50Z  2020-11-24T19:41:50Z  null                  Argo Tunnel API Token for ***
00000000000000000000000000000000  2020-09-12T22:01:42Z  2020-09-12T22:01:42Z  2020-09-12T22:26:44Z  *****************************
00000000000000000000000000000000  2020-08-10T23:28:33Z  2020-08-10T23:28:33Z  null                  Argo Tunnel API Token for ***
00000000000000000000000000000000  2020-08-09T20:16:40Z  2020-08-09T20:16:40Z  null                  Argo Tunnel API Token for ***
00000000000000000000000000000000  2020-03-25T17:27:56Z  2020-03-25T17:31:26Z  2020-03-25T17:54:46Z  *****************************
$
```

I hope that helps you.
