### ISSUE TITLE
Method is Not Allowed Error is Not Clear for DNS Updates

### ISSUE THREAD

**Issue by jouellnyc** [cloudflare/python-cloudflare#141]
Trying to update a DNS Record:

```
import Cloudflare
ZONE=“mydom”
cf = Cloudflare.Cloudflare(email=‘myemail’, token=GLOBAL_API_KEY)
zones = cf.zones.get(params = {‘name’:ZONE,‘per_page’:1})
zone = zones[0]
zone_id = zone[‘id’]
dns_record = {‘name’:‘BLAH’, ‘type’:‘A’, ‘ttl’: 120, ‘content’: ‘192.168.1.7’}
cf.zones.dns_records.put(zone_id, data=dns_record)

```
 - Using a Bearer Token yields  "PUT method not allowed for the api_token authentication scheme" (not shown above).
 - However using the Global API yields: "CloudFlare.exceptions.CloudFlareAPIError: method_not_allowed"
 
So it's not very clear what is accepted to update a  dns record via the Python Wrapper

It seems like a PUT would be the right thing as per  https://api.cloudflare.com/#dns-records-for-a-zone-update-dns-record

**Comment by mahtin** [comment]
Just add the dns_record's I'd value to the call. See this line:
```

dns_record = cf.zones.dns_records.put(zone_id, dns_record_id, data=dns_record)
```

It's in the dynamic dns example in the examples directory.

**Comment by jouellnyc** [comment]
Ah! Thank you. I did look in the examples but clearly not hard enough.
