### ISSUE TITLE
raw mode for paginated requests not working for me

### ISSUE THREAD

**Issue by iojeda** [cloudflare/python-cloudflare#142]
First of all thanks for your work in this wrapper it makes interacting with Cloudflare easier.

I am having an issue when trying to paginate, please see below screenshot of debugmode for a raw paginated dns request

![image](https://user-images.githubusercontent.com/5243583/162151017-8f9f27a1-de52-4dec-8b69-6fb0b9590333.png)
As you can see I defined 500 results per page but I am only getting 100 per page.
Also on second iteration of the loop I still get the 1st page although I am requesting the second page.

![image](https://user-images.githubusercontent.com/5243583/162152862-30e886bd-d723-41b3-8ccc-5381aa9c1e89.png)

**Is there something wrong in my code?**
**Could you please point me in the right direction?**

I apologize in case this is not the place to raise this kind of questions but I don't know anywhere else to ask.
Thanks in advance.

**Comment by iojeda** [comment]
Hi I figured out what was the issue 🤦‍♂️.
In my code (line 30) I was using _cf.zones.dns_records_ instead of _cf.zones.dns_records.get_

So working code for line 30 is:
**raw_results = cf.zones.dns_records.get(zoneid,params={'per_page':500,'page':page_number})**

Hope this helps someone else 😄

**Comment by mahtin** [comment]
@iojeda - I'm glad you have working code; however, I can actually see why this failed for you. There's a typo in the code (that was introduced recently). I will go add a fix quickly. The `.get()` form is the best way to to code; however these two calls should be the same (once the bug is fixed):

```
    r = cf.zones.dns_records(zone_id, params=...)
    r = cf.zones.dns_records.get(zone_id, params=...)
 ```
Sorry! Stay tuned.

**Comment by mahtin** [comment]
OK - fixed. Release `2.9.10` onto (PyPI)[https://pypi.org/project/cloudflare/] and here on GitHub. You can now call with or without the `.get` again.
