### ISSUE TITLE
[Question] How do you so cleverly auto convert the API call to be dot notation python command?

### ISSUE THREAD

**Issue by simkimsia** [cloudflare/python-cloudflare#145]
I am coming from this comment https://github.com/cloudflare/python-cloudflare/issues/144#issuecomment-1161970663

I'm just so impressed by how a API call url is changed so seamlessly into the dot notation chaining in Python.

Like how `GET user/tokens/verify` becomes

```python
cf = CloudFlare.CloudFlare(token=legal_token)
response = cf.user.tokens.verify() ## looks exactly the same as the API url!
```

Because typically libraries that call public APIs end up have their own programming interfaces instead. So for this to be consistent with the underlying API is just :chef_kiss: awesome.

I was wondering how this is done. I suspect this file `api_v4.py` is key https://github.com/cloudflare/python-cloudflare/blob/master/CloudFlare/api_v4.py but i cannot be sure.

Also I don't know how you go from the CloudFlare class to call this. Though I did notice this line https://github.com/cloudflare/python-cloudflare/blob/b70b5209664dc64ae4f0e5773806aec05b799cbd/CloudFlare/cloudflare.py#L933

Is that basically all there is to it?

I can use the same technique to write the same kind of wrapper for other publicly available API like GitHub's API right?

**Comment by mahtin** [comment]
In the `api_v4.py` file, look at the lines like this:
```
    self.add('AUTH', 'zones')
    self.add('AUTH', 'zones', 'pagerules')
```
The `add()` method will dynamically create a new method based on the argument strings. The reason for more than one parameter to the `add()` method is signal where a required `:id` is required by the API. For this example, look at https://api.cloudflare.com/#page-rules-get-page-rules and it's call to the API:
```
    GET zones/:zone_identifier/pagerules
```
There are 370+ (now 430+ with `/radar` released) API endpoints created via this code. You can see the list of call implemented by the call via:
```
$ cli4 --dump | more
/accounts
/accounts/:id/access/apps
/accounts/:id/access/apps/:id/ca
/accounts/:id/access/apps/:id/policies
/accounts/:id/access/apps/:id/revoke_tokens
/accounts/:id/access/apps/:id/user_policy_checks
/accounts/:id/access/bookmarks
...
$
```

I hope that helps.
