### ISSUE TITLE
no signature for 2.9.x releases

### ISSUE THREAD

**Issue by FelixSchwarz** [cloudflare/python-cloudflare#146]
Releases for 2.8.x were signed with GPG but 2.9.x releases are not. For Fedora it would be nice if all release binaries were signed (+ uploaded to pypi). Would you mind signing future releases again?

Benefit for Fedora/distros: We can be sure that no one tampered with the tarball which is distributed to quite a few users.

**Comment by mahtin** [comment]
Agree 100%.

Sadly this is a function of the fact that while I still actively maintain this s/w (with Cloudflare's knowledge), I've now retired from Cloudflare. I can sign new releases with my personal email key; however, I can't sign new releases with my old @cloudflare key. I believe I can get this easily approved as my personal email address has been somewhat included in the setup.py & Makefile since day zero.

I will endeavor to work on doing exactly this later next month (I'm on vacation presently).

Stay tuned.

**Comment by FelixSchwarz** [comment]
A personal key would be totally fine by me. We (Fedora) just need to know which key is legitimate (e.g. by mentioning the key ID in the documentation or in release announcements.

**Comment by mahtin** [comment]
@FelixSchwarz - please try now. The latest release `2.10.1` is now signed. Please let me know if this successfully makes it way into Fedora. It looks like it's ready via https://bugzilla.redhat.com/buglist.cgi?bug_status=NEW&bug_status=ASSIGNED&classification=Fedora&component=python-cloudflare&product=Fedora&product=Fedora%20EPEL and https://src.fedoraproject.org/rpms/python-cloudflare

Thanks!

**Comment by FelixSchwarz** [comment]
Thank you very much for signing the new release. Two questions:

- Could you also sign the pypi release? This is a bit easier to consume for (though github works as well)
- Can you mention your key ID here?

**Comment by mahtin** [comment]
I finally gave this a try - i.e signing the `pypi` upload via `twine ... --sign ...` and while I seems to produce a correct `.asc` file locally, it does not seem to produce a valid `.asc` file online.

I did this on release `2.12.4`.

```
$ cat dist/cloudflare-2.12.4.tar.gz.asc 
-----BEGIN PGP SIGNATURE-----

iQIzBAABCgAdFiEEfqE5xAwchC+dQar5SjSSXQUXKFkFAmUM8iIACgkQSjSSXQUX
KFlsAg/7B7y9osO9Q2ZvU3fDy1tL4SnuFumZ4KJctFg+M13nWYZAIkqzWi3ZG+1I
x0HUL3SisoVttMz0tI1n6Z8Kgr+PfLRBbJfvVwbHL1naYNArIv0FJrMB11pWQ92d
1FoJGhtAeM/xT4UQW+cI7sI+u0Rz+PVEG0Gb7Kcrxkv5/PPiXRqb1K0syu5IshMF
94Mir6TYPcr7ClKyzjOnxWfph/0ogjOcog6s6Ol9pVEEHtn7HbbrAPupWz2EiYwX
l3nsxyK5NedDRkNwVbg9TufYx72uZ6vxiJfMxRd0cQEwFi/XBbqpRqzwYtcvXSn3
WKBLEPuW3+wkkxTMxIdDtvj+VX6R4DS0y5ZX4S1Hqw60XgqVnnDYRfMWmbTMBISS
+xMe84sW+dWsMBmI2Otn4IVaSk0udLXkNnCc09VdkZKew6qpt5fmMkhlxuiAo7qq
MFYPJXkBfUgNAameYMuHhfV1TXoBONOYpx2grIYgj56m2IfOs0KzCyMnlM9WVQff
9M1boYqAPb96cmDQKwmh8oxQrWFDXreR4FLKp/+BusPG78EUIyfDQQ+I78DH4tNA
7YmE9E4bpnERvJzcYtJbOGzvteqbyK0CTuAxOPwM12/OHoXbihXLC6i0GemueL4Z
DCAjeu/L5GCaOc+TlJOZPrjaBpm318aB0e1DRl11qkTYVbmvhP0=
=LmwK
-----END PGP SIGNATURE-----
```

The `.asc` file is not listed at https://pypi.org/project/cloudflare/#files (others have said this). You can use the filename listed on that page to craft a valid download. The download filename is https://files.pythonhosted.org/packages/1e/88/a1678ab307552afa69b39156b5c6e33ab77ae333ad183ce279a6006ca491/cloudflare-2.12.4.tar.gz and hence ... 

```
$ curl -RL https://files.pythonhosted.org/packages/1e/88/a1678ab307552afa69b39156b5c6e33ab77ae333ad183ce279a6006ca491/cloudflare-2.12.4.tar.gz.asc
<?xml version="1.0" encoding="UTF-8"?>
<Error>
  <Code>NoSuchKey</Code>
  <Message>The specified key does not exist.</Message>
  <Key>packages/1e/88/a1678ab307552afa69b39156b5c6e33ab77ae333ad183ce279a6006ca491/cloudflare-2.12.4.tar.gz.asc</Key>
  <RequestId>10F6N2KB75J1FP5P</RequestId>
  <HostId>nWMSUP3bVz/yj7cu0sJK8AnnfBRbC5iSU9Nk2OlcMX6Bfa7x+RdG6aSdYDc93xji4leqG07uifc=</HostId>
</Error>
$
```

(I cleaned up the output to make it readable - but basically it's an error and not a valid `.asc`. 

Sigh.

So while the GitHub release `2.12.4` is signed. I don't think the PyPi release is signed.

**Comment by mahtin** [comment]
I should have checked my email. 

```
From: PyPI <noreply@pypi.org>
Date: Thu, Sep 21, 2023 at 6:47 PM
Subject: [PyPI] Unsupported GPG signature uploaded to PyPI
To: Martin J Levy <mahtin@mahtin.com>

What?

During your recent upload of cloudflare to PyPI, we noticed you uploaded a GPG signature. However, support for GPG signatures has been removed from PyPI.

What should I do?

While uploads will continue to work, any signatures uploaded to PyPI will be discarded. It is recommended to no longer upload signatures to PyPI.
```

Well there you go. I will remove the `--sign` and call this effort off.

**Comment by FelixSchwarz** [comment]
Thank you so much for trying - I should have remembered this ticket when the pypi change came into effect, sorry for the extra work. I'm still sad that pypi removed signature support. For my Fedora packages I'll try to use signed tarballs from github if these are available so just signing the github release would not be for naught.
