### ISSUE TITLE
Unable to connect to logpush/edge enpoint via cli4

### ISSUE THREAD

**Issue by antigenius0910** [cloudflare/python-cloudflare#150]
Trying to check and configure logpush instant jobs (https://developers.cloudflare.com/logs/instant-logs) and was hoping to use cli4 to do it quickly, but it doesn't know the logpush/edge endpoint. 

It just returns the error /zones/:zoneid/logpush/edge - not found. 
Confirmed that it does work as expected via curl.

Tested using version 2.10.2

```
~ ᐅ cli4 -v zones/:$CLOUDFLARE_ZONE_ID/logpush/edge/jobs
cli4: /zones/:$CLOUDFLARE_ZONE_ID/logpush/edge - not found
```

**Comment by mahtin** [comment]
The Python Cloudflare libraries are build from the contents of the https://api.cloudflare.com website. Sadly, the `/zones/:zoneid/logpush/edge` call has not been documented on that page. It's only on https://developers.cloudflare.com/logs/instant-logs within the developers area. (Yes, there's more than one place you need to read if you want to work with Cloudflare API's). I'll do two things.

1) I'll notify Cloudflare.
2) I'll code it up from the developers page and report back here if I can push it cleanly to GitHub & PyPI.

More later

**Comment by antigenius0910** [comment]
thanks so much for the help @mahtin !! 
and yes. it needs a enterprise account. reference here https://blog.cloudflare.com/instant-logs-on-the-command-line/

I also create a simple python script here https://gist.github.com/antigenius0910/2528b68510a522c4f7ffd22d32e06c49 as well but thinking on cli4 it could beneficial for more people

**Comment by mahtin** [comment]
OK - it's working. I will push some code later tonight as I have a few other items to add.

We start with an empty slate:
```
$ cli4 /zones/:███████████.com/logpush/edge/jobs | jq .
[]
$
```
Then we add monitoring:
```
$ cli4 --post \
	='{
		"fields": "ClientIP,ClientRequestHost,ClientRequestMethod,ClientRequestURI,EdgeEndTimestamp,EdgeResponseBytes,EdgeResponseStatus,EdgeStartTimestamp,RayID",
		"sample": 1,
		"filter": "",
		"kind": "instant-logs"
	}' \
	/zones/:███████████.com/logpush/edge/jobs | jq .
{
  "destination_conf": "wss://logs.cloudflare.com/instant-logs/ws/sessions/████████████████████████████████",
  "fields": "ClientIP,ClientRequestHost,ClientRequestMethod,ClientRequestURI,EdgeEndTimestamp,EdgeResponseBytes,EdgeResponseStatus,EdgeStartTimestamp,RayID",
  "filter": "",
  "kind": "instant-logs",
  "sample": 1,
  "session_id": "████████████████████████████████"
}
$
```
$
Then we can see the results:
```
$ cli4 /zones/:███████████.com/logpush/edge/jobs | jq .
[
  {
    "fields": "ClientIP,ClientRequestHost,ClientRequestMethod,ClientRequestURI,EdgeEndTimestamp,EdgeResponseBytes,EdgeResponseStatus,EdgeStartTimestamp,RayID",
    "filter": "",
    "kind": "instant-logs",
    "sample": 1,
    "session_id": "████████████████████████████████"
  }
]
$
```

Yippee! Sadly, this call does not match the normal param processing for other Cloudflare calls. Hence the need to add code.

I'll push later today.

**Comment by mahtin** [comment]
Release 2.10.3 is now released (to Github and PyPl). Enjoy!
