### ISSUE TITLE
edit firewall rules

### ISSUE THREAD

**Issue by net47** [cloudflare/python-cloudflare#154]
Hello,

I see that there's the possibility to interact with firewall rules:

https://github.com/cloudflare/python-cloudflare/blob/b70b5209664dc64ae4f0e5773806aec05b799cbd/CloudFlare/api_v4.py#L172

How would be the equivalent python wrapper code for:

```
curl -s --request PUT \
  --url https://api.cloudflare.com/client/v4/zones/<zone-id>/firewall/rules \
  --header 'Authorization: Bearer <auth-code>' \
  --header 'Content-Type: application/json' \
  -d '[
      {
        "id": <rule-id>,
        "paused": false,
        "description": "carrier",
        "action": "block",
        "priority": null,
        "filter": {
          "id": <filter-id>,
          "expression": <my-expression>,
          "paused": false,
          "description": ""
        }
      }
    ]'
```
I was starting with that code but don't know how to move on:

```
cf = CloudFlare.CloudFlare(email=<my-email>, key=<my-key>)
waf = cf.zones.firewall.rules.set(<abc>)...
```
Maybe someone can help me with that?
Thanks!

**Comment by mahtin** [comment]
I think most of what you need to know is somewhere within the README file.
Plus, you should also know about the older https://api.cloudflare.com/#firewall-rules-list-firewall-rules page and the new https://developers.cloudflare.com/api/operations/firewall-rules-list-firewall-rules page that just came out.
I believe the following code is what you need (the key part is `cf.zones.firewall.rules.post(zone_id, data=data)`.
```
import CloudFlare

cf=CloudFlare.CloudFlare()

my_filter = {
    # 'id': '372e67954025e0ba6aaa6d586b9e0b61',
    'expression': '(http.request.uri.path ~ ".*wp-login.php" or http.request.uri.path ~ ".*xmlrpc.php") and ip.addr ne 172.16.22.155',
    'paused': False,
    # 'description': 'Restrict access from these browsers on this address range.',
    # 'ref': 'FIL-100',
}

zone_id = '00000000000000000000000000000000'

data = {
    'action': 'block',
    'filter': my_filter,
    # 'description': 'testing123',
    # 'products': ['waf'],
    # 'priority': 1,
    # 'paused': False,
}

r = cf.zones.firewall.rules.post(zone_id, data=data)
print(r)
```

However, it sadly causes an error (`firewallrules.api.malformed_request_body` to be exact). But the code structure is correct. I will go look at this some more after dinner.

**Comment by mahtin** [comment]
Please see edited previous comment. Let close if you get your code working.

**Comment by net47** [comment]
Thanks a lot mahtin, I just tried it with my code:

```
import CloudFlare

cf = CloudFlare.CloudFlare(email="abc", key="abc")
zone_id = "111111111"

filterdata = {
        'id': 'abc',
        'expression': 'ip.src ne 1.2.3.4)',
        'paused': 'false',
        'description': ''
    }

data = [
    {
        'id': 'abc',
        'paused': 'false',
        'description': 'carrier',
        'action': 'block',
        'priority': 'null',
        'filter': filterdata,
    }
]

waf = cf.zones.firewall.rules.post(zone_id, data=data)
```
Result:
```
CloudFlare.exceptions.CloudFlareAPIError: firewallrules.api.malformed_request_body
```
What I see, this is the same as you posted, the only difference is that you first delete all existing firewall filters and rules. Is this mandatory?

**Comment by mahtin** [comment]
The delete was just me cleaning up. There's no need for that in production code (unless you need to delete a filter or firewall). 

Some thoughts:

Don't set `id`, it's not needed as it's allocated by the API. 

You have `'paused': 'false'` - in Python use `False` (no quotes).

You have `'priority': 'null'` - that's not valid. Use `None` as the value however, I think this is an integer, so use `50` or don't set it.

But more importantly, you have `'expression': 'ip.src ne 1.2.3.4)'` - there's a `)` that's not balanced. 

Try again with these fixes.

**Comment by net47** [comment]
Thanks a lot, that did the trick - my expression was faulty. 

get WAF rules:
```
get_rules = cf.zones.firewall.rules.get(zone_id)
```
set specific WAF rule:
```
set_rule = = cf.zones.firewall.rules.put(zone_id, data=data)
```

**Comment by mahtin** [comment]
The `examples` folder now includes https://github.com/cloudflare/python-cloudflare/blob/a8872852966b4ff4674cf3c9682adf209417d48f/examples/example_firewall_rules.py
