### ISSUE TITLE
How to upload Worker module?

### ISSUE THREAD

**Issue by mlejva** [cloudflare/python-cloudflare#157]
I'm trying to create a new worker using this wrapper but it looks like that all requests from this wrapper are sent with the 
`content-type` header set to 

```
"Content-Type: application/json"
```

However, according to docs, the code data when creating new workers using [this endpoint](https://developers.cloudflare.com/api/operations/worker-script-upload-worker-module) must be sent as form data
```
'Content-Type: multipart/form-data'
```

This is my code
```python
cf = CloudFlare.CloudFlare(debug=True)
cf_acc_id = os.environ.get("CLOUDFLARE_ACC_ID")
data = {
    "index.js": """export default {{
  async fetch(request) {{
    return new Response("Hello World!");
  }},
}};""",
    "metadata": {"main_module": "index.js"},
}
r = cf.accounts.workers.scripts.put(cf_acc_id, "my_script", data=data)
```

The debug info coming from the wrapper:
```
2023-03-08 20:00:31,105:DEBUG - Call: emulated curl command ...
        curl -X PUT "https://api.cloudflare.com/client/v4/accounts/5b4d35dabe176b6a4017c8e38351a548/workers/scripts/my_script" \
             -H "User-Agent: python-cloudflare/2.11.1/python-requests/2.28.2/python/3.10.8" \
             -H "Content-Type: application/json" \
             -H "X-Auth-Email: REDACTED \
             -H "X-Auth-Key: REDACTED" \
             --data '{"index.js": "export default {{\n  async fetch(request) {{\n    return new Response(\"Hello World!\");\n  }},\n}};", "metadata": {"main_module": "index.js"}}'
```

Am I missing anything or is this a bug? Is there a workaround for now?

**Comment by mahtin** [comment]
You should really use [Wrangler](https://developers.cloudflare.com/workers/) for workers uploads. Because Wrangler went from v1 to v2, I think the Python code isn't going to run perfectly. See the [blog post](https://blog.cloudflare.com/deprecating-wrangler-v1/) about this.

**Comment by mahtin** [comment]
I'm going to stick with my original answer and say use Wrangler. However, if you want to get `multipart/form-data` into the headers, then write your content to a file and then upload the file via something like this:
```
     r = cf.accounts.workers.scripts.post(cf_acc_id, "my_script", files={'file':fd})
```
However, I've not done this (as I use Wrangler). 

Good luck!
