### ISSUE TITLE
General question - future of the python-cloudflare wrapper

### ISSUE THREAD

**Issue by AntonDykyi** [cloudflare/python-cloudflare#158]
Hey Cloudflare team, I see this repo is not super active as compared to [cloudflare-go](https://github.com/cloudflare/cloudflare-go). What is Cloudflare's view on this? Are you nudging people towards using the go library instead of the python one?

**Comment by mahtin** [comment]
As there's been a few updates this past week (including adding a ton more api endpoints, I'm closing this issue.
