### ISSUE TITLE
Proxy Configuration

### ISSUE THREAD

**Issue by WebTemplarAsylum** [cloudflare/python-cloudflare#160]
**Cause**
It does not appear that the python client library supports proxy settings.
During request call from the python-cloudflare project any requests that originate behind
a proxy the request with errors similar to the below.

Traceback (most recent call last):
  File "CloudflareTest.py", line 20, in <module>
    main()
  File "CloudflareTest.py", line 25, in main
    zones = cf.zones.get(params={'per_page':50})
  File "/usr/lib/python3.7/site-packages/CloudFlare/cloudflare.py", line 674, in get
    return self._base.do_auth('GET', self._parts, [identifier1, identifier2, identifier3, identifier4], params, data)
  File "/usr/lib/python3.7/site-packages/CloudFlare/cloudflare.py", line 129, in do_auth
    return self._call(method, headers, parts, identifiers, params, data, files)
  File "/usr/lib/python3.7/site-packages/CloudFlare/cloudflare.py", line 431, in _call
    response_data = self._raw(method, headers, parts, identifiers, params, data, files)
  File "/usr/lib/python3.7/site-packages/CloudFlare/cloudflare.py", line 286, in _raw
    params, data, files)
  File "/usr/lib/python3.7/site-packages/CloudFlare/cloudflare.py", line 206, in _call_network
    raise CloudFlareAPIError(0, e)
CloudFlare.exceptions.CloudFlareAPIError: HTTPSConnectionPool(host='api.cloudflare.com', port=443): 
Max retries exceeded with url: /client/v4/zones?per_page=50 
(Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x6fffff6ee490>: 
Failed to establish a new connection: **[Errno 114] Network is unreachable'**))

**Benefit**
Adding this feature will provide a wider use-case for teams to use this project to automate many
manual tasks that are currently done from manually logging into their dashboard.

**Comment by mahtin** [comment]
Hello @WebTemplarAsylum,

It looks like it work with the present code. First off - check it normally works.
```
$ cli4 /ips | wc -l
      29
$
```
Now lets install a null route for the Cloudflare network on a local machine such that direct access does not work anymore. Note that this `99` method is HORRID - but it works (as long as you undo it later).
```
$ sudo route add 104.19.0.0/16 10.99.99.99
add net 104.19.0.0: gateway 10.99.99.99
$ sudo route add -inet6 2606:4700:300a::/48 2001:9999::9999
add net 2606:4700:300a::/48: gateway 2001:9999::9999
$ cli4 /ips | wc -l
cli4: /ips - 0 HTTPSConnectionPool(host='api.cloudflare.com', port=443): Max retries exceeded with url: /client/v4/ips (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1061faa10>: Failed to establish a new connection: [Errno 51] Network is unreachable'))
       0
$
```
Cool (kinda) - we have no access to Cloudflare presently! YIKES!

As I run a proxy on a small Raspberry Pi on my local network; let's use that. I run `Squid Cache 4.13-10+deb11u2`
```
$ HTTPS_PROXY=http://pi-metal.local:3128 python -m cli4 /ips | wc -l
      29
$
```
Yup - it works. Please check your proxy can do full HTTPS transfers. Look below for the `TCP_TUNNEL` message.

Now undo everything!
```
$ sudo route delete 104.19.0.0/16 10.99.99.99
delete net 104.19.0.0: gateway 10.99.99.99
$ sudo route delete -inet6 2606:4700:300a::/48 2001:9999::9999
delete net 2606:4700:300a::/48: gateway 2001:9999::9999
Martins-MacBook-Air:python-cloudflare martin$ 
```
Test it again to make sure we are back to normal
```
$ cli4 /ips | wc -l
      29
$
```

You can also check this with a `curl` command and the `--proxy` flag.

What proxy are you running? Do you see good access in the logs? My logs look like this:
```
1679427895.725    231 2601:647:████:████:████:████:████:████ TCP_TUNNEL/200 3950 CONNECT api.cloudflare.com:443 - HIER_DIRECT/2606:4700:300a::6813:c01d -
1679427901.460    343 2601:647:████:████:████:████:████:████ TCP_TUNNEL/200 3950 CONNECT api.cloudflare.com:443 - HIER_DIRECT/2606:4700:300a::6813:c01d -
```

Let me know.

**Comment by WebTemplarAsylum** [comment]
Good afternoon Martin,
My apologies. Yes your original solution was great. Thank you for the assistance.
Reginald
    On Wednesday, May 24, 2023 at 12:03:57 PM CDT, Martin J. Levy ***@***.***> wrote:  
 
 


@WebTemplarAsylum - nothing heard back. I assume you're working fine. I'm close this issue. Open it again with specific info if you're still having issues after read my response above.
