### ISSUE TITLE
New rulesets API endpoints for WAF configuration

### ISSUE THREAD

**Issue by dcruzrinkel** [cloudflare/python-cloudflare#161]
Hello there.

Will this be updated to support the new ruleset API calls just released today?

I imagine the zones.filters will be removed and just use the new syntax?

**Comment by mahtin** [comment]
I think the key part of the statement there is "today". :) The answer is yes; but give me a bit in order to code and test it. I myself also got the notice this morning. Looks very cool!

**Comment by dcruzrinkel** [comment]
Thanks! ;-)
