### ISSUE TITLE
 package  add  (http/socks5) network proxy parameters 

### ISSUE THREAD

**Issue by langzisuifeng** [cloudflare/python-cloudflare#164]
May I ask if this package can be added to set (http/socks5) network proxy parameters No, in some areas, api.cloudflare.com:443 often fails to connect to the network.

**Comment by mahtin** [comment]
Please see the notes about environmental value `HTTPS_PROXY` on issue #160. This should provide you everything you need. Sorry this has not made it to the README file yet.

**Comment by langzisuifeng** [comment]
It is true that environment variables can be set by using the cli method, but is there a more convenient way to set the proxy when the python script is used to run the calling method of calling the library package?

**Comment by mahtin** [comment]
You can use the following Python code within your `main()` function.

```
import os

os.environ['HTTPS_PROXY'] = 'http://your-squid-proxy-machine.local:3128'
```

Make sure that's before any network call or Cloudflare call.

**Comment by langzisuifeng** [comment]
Thanks, this solved my problem！
