### ISSUE TITLE
Package no longer works after updating pip packages

### ISSUE THREAD

**Issue by Pikamander2** [cloudflare/python-cloudflare#166]
A few days ago, I updated all of my pip packages to the latest version. I'm now getting this error whenever I try to run `import CloudFlare`:

```
Traceback (most recent call last):
  File "C:\Users\Myname\Dropbox\Sitebolts\Maintenance\Cloudflare backup maker\cloudflare-backup-maker\cloudflare-backup-maker.py", line 1, in <module>
    import CloudFlare
  File "C:\Users\Myname\AppData\Roaming\Python\Python39\site-packages\CloudFlare\__init__.py", line 6, in <module>
    from .cloudflare import CloudFlare
  File "C:\Users\Myname\AppData\Roaming\Python\Python39\site-packages\CloudFlare\cloudflare.py", line 8, in <module>
    from .network import CFnetwork
  File "C:\Users\Myname\AppData\Roaming\Python\Python39\site-packages\CloudFlare\network.py", line 6, in <module>
    from .exceptions import CloudFlareAPIError
ModuleNotFoundError: No module named 'CloudFlare.exceptions'
```

I tried uninstalling and reinstalling the package but the issue persists.

I'm using Windows 10 and Python 3.9.0.

**Comment by Pikamander2** [comment]
It seems to work fine on a completely fresh install of Windows, but what would be the cause of that error and how can I or you get it fixed?

**Comment by Pikamander2** [comment]
I tried installing several older versions but ran into the same error.

**Comment by Pikamander2** [comment]
I'm going to install Python 3.11 soon anyway, which will almost certainly fix it. But I would recommend checking to see if you can reproduce the issue on Python 3.9.0 in case some dependencies need to be corrected or something.

**Comment by mahtin** [comment]
Looks like you had an install that's missing one specific file. 
```
    from .exceptions import CloudFlareAPIError
ModuleNotFoundError: No module named 'CloudFlare.exceptions'
```
The `exceptions.py` file. That's weird as all the other files are there from the Cloudflare library. I'd manually check and see what happened. Your package has been corrupted.

To be honest that's about as far as I can help. The install worked; but you ended up with a single file being deleted. Which is weird.

**Comment by mahtin** [comment]
I did a fresh install on a machine that's never had the Cloudflare Python package ever installed on it (in fact it's the first time Python was ever run on this machine - it's Win7 no less!)

The install does indeed install all the correct files. I'm not sure what's going on with your install; however, I could recommend `pip uninstall` and then `pip install`. But that should not be needed. Sigh.

My results below:

```
U:\Users\██████████████>pip show -f cloudflare
Name: cloudflare
Version: 2.11.7 
Summary: Python wrapper for the Cloudflare v4 API
Home-page: https://github.com/cloudflare/python-cloudflare
Author: Martin J. Levy
Author-email: mahtin@mahtin.com
License: MIT
Location: u:\users\██████████████\appdata\local\programs\python\python38\lib\site-packages
Requires: beautifulsoup4, jsonlines, pyyaml, requests
Required-by:
Files:
  ..\..\Scripts\cli4.exe
  ..\..\share\man\man1\cli4.1
  CloudFlare\__init__.py
  ...
  CloudFlare\api_decode_from_openapi.py
  CloudFlare\api_decode_from_web.py
  CloudFlare\api_extras.py
  CloudFlare\api_v4.py
  CloudFlare\cloudflare.py
  CloudFlare\exceptions.py
  CloudFlare\logging_helper.py
  CloudFlare\network.py
  CloudFlare\read_configs.py
  CloudFlare\utils.py
  ...

U:\Users\██████████████>
```

This did produce a working setup.
```
U:\Users\██████████████>cli4 /ips
{
    "etag": "38f79d050aa027e3be3865e495dcc9bc",
    "ipv4_cidrs": [
...
}
U:\Users\██████████████>
```

**Comment by mahtin** [comment]
I also tested with Win11 and Python 3.11 - same same - it worked. Please reopen with more info if this is still an issue. Thanks,
