### ISSUE TITLE
I'm not getting the right DNS record_id

### ISSUE THREAD

**Issue by alfredocambera** [cloudflare/python-cloudflare#169]
While fixing a module in Terraform I found that the record_id returned by python-cloudflare was different from the one that I was getting directly from fetching the record_id using curl.

The curious thing is that after getting the right record using curl, a second execution of my python code would return the right record_id.

How did I know the record_id was incorrect? As terraform import would complain about a non-existent record in the specified zone while importing an existing record.

My code doesn't do anything special (https://gist.github.com/alfredocambera/6349b363750beabdf73683bd6c1d94db).

Here the shell code:

```
#!/usr/bin/env bash

NAME="$1"
ZONE="USE_A_REAL_ZONE_ID_HERE" #

curl -s \
  --request GET \
  --url     "https://api.cloudflare.com/client/v4/zones/${ZONE}/dns_records?page=1&name=$NAME" \
  --header  'Content-Type: application/json' \
  --header "Authorization: Bearer USE_TOUR_OWN_TOKEN"
```

Is there a reason for this?

**Comment by mahtin** [comment]
I'm sorry I don't think I can replicate your issue. I played with https://gist.github.com/alfredocambera/6349b363750beabdf73683bd6c1d94db a lot (adjusting the code along. the way). I always get the same (correct) textual output.
