### ISSUE TITLE
How to access R2 storage to perform CRUD on Bucket and Objects

### ISSUE THREAD

**Issue by salman161222** [cloudflare/python-cloudflare#171]
@mahtin: Please help

How to access R2 storage to perform CRUD on Bucket and Objects.

The documentation is not at all helping out.

Please share a sample code.

**I tried below code:**

import json
import CloudFlare

def main():
    cf = CloudFlare.CloudFlare()
    zones = cf.accounts_r2.get(params={'per_page':5})
    print(f"{ cf.api_from_web()}")

if __name__ == '__main__':
    main()

    
 **Error getting**
root@CGX-Quadcore:~/CGX_API# python3 test.py 
Traceback (most recent call last):
  File "/root/CGX_API/test.py", line 11, in <module>
    main()
  File "/root/CGX_API/test.py", line 6, in main
    zones = cf.accounts_r2.get(params={'per_page':5})
  File "/usr/local/lib/python3.9/dist-packages/CloudFlare/cloudflare.py", line 1014, in __getattr__
    raise AttributeError(key)
AttributeError: accounts_r2

I tried Other way also:

import requests

api_token = "your-api-token"

url = "https://api.cloudflare.com/client/v4/user/tokens/verify"

headers = {
    "Authorization": f"Bearer {api_token}",
}

response = requests.get(url, headers=headers)

if response.status_code == 200:
    print("GET request successful.")
    print("Response content:")
    print(response.text)
else:
    print("GET request failed. Status code:", response.status_code)
    print("Response:", response.text)
    
    **Error:**

root@CGX-Quadcore:~/CGX_API# python3 test.py 
GET request failed. Status code: 400
Response: {"success":false,"errors":[{"code":6003,"message":"Invalid request headers","error_chain":[{"code":6111,"message":"Invalid format for Authorization header"}]}],"messages":[],"result":null}

**Comment by mahtin** [comment]
Hello,

Please review the examples folder and the README. You will see that python calls to the Cloudflare API follow Python class syntax. Here's an example for you to look at:

```
#!/usr/bin/env python
""" dump r2 info """

import sys
import json
import CloudFlare

def main():
    """ main() """

    try:
        account_name = sys.argv[1]
    except IndexError:
        account_name = ''

    cf = CloudFlare.CloudFlare()

    account_id = get_account_id(cf, account_name)

    buckets = cf.accounts.r2.buckets(account_id)

    print(json.dumps(buckets, indent=4))

    for bucket in buckets['buckets']:
        bucket_name = bucket['name']
        print('%s:' % (bucket_name))
        objects = cf.accounts.r2.buckets.objects(account_id, bucket_name)
        print(json.dumps(objects, indent=4))
        print('')

    exit(0)

def get_account_id(cf, account_name):
    """ get_acount_id() """

    if account_name == '':
        params = None
    else:
        params = {'name': account_name}

    try:
        accounts = cf.accounts.get(params=params)
    except CloudFlare.exceptions.CloudFlareAPIError as e:
        exit('/accounts %d %s - api call failed' % (e, e))
    except Exception as e:
        exit('/accounts.get - %s - api call failed' % (e))

    if len(accounts) == 0:
        exit('/accounts.get - %s - account not found' % (account_name))

    if account_name == '' and len(accounts) != 1:
        exit('/accounts.get - api call returned %d items - please choose account name from %s' % (len(accounts), [a['name'] for a in accounts]))

    account_id = accounts[0]['id']
    return account_id

if __name__ == '__main__':
    main()
```
When run it can produce the following results:
```
$ python r2example.py
{
    "buckets": [
        {
            "name": "astrophotography",
            "creation_date": "2022-12-11T13:21:45.291Z"
        },
        {
            "name": "via-dashboard",
            "creation_date": "2022-08-07T20:22:23.688Z"
        },
        {
            "name": "wwvb-60-khz",
            "creation_date": "2023-02-21T20:12:01.943Z"
        }
    ]
}
...
via-dashboard:
[
    {
        "key": "hello-world.txt",
        "etag": "2cad20c19a8eb9bb11a9f76527aec9bc",
        "last_modified": "2022-08-07T21:25:20.306Z",
        "size": 12,
        "http_metadata": {
            "contentType": "application/javascript"
        },
        "custom_metadata": {}
    },
]
...
```
Your output will (of course) vary.

I hope this helps.

**Comment by salman161222** [comment]
Thanks for providing sample code @mahtin , another error:

import sys
import json
import CloudFlare

cf = CloudFlare.CloudFlare()



def get_account_id(cf, account_name):
    """ get_acount_id() """

    if account_name == '':
        params = None
    else:
        params = {'name': account_name}

    try:
        accounts = cf.accounts.get(params=params)
    except CloudFlare.exceptions.CloudFlareAPIError as e:
        exit('/accounts %d %s - api call failed' % (e, e))
    except Exception as e:
        exit('/accounts.get - %s - api call failed' % (e))

    if len(accounts) == 0:
        exit('/accounts.get - %s - account not found' % (account_name))

    if account_name == '' and len(accounts) != 1:
        exit('/accounts.get - api call returned %d items - please choose account name from %s' % (len(accounts), [a['name'] for a in accounts]))

    account_id = accounts[0]['id']
    return account_id

account_id = get_account_id(cf, '<<<<MY_ACCOUNT NAME>>>>')


**ERROR**

/accounts 9103 Unknown X-Auth-Key or X-Auth-Email - api call failed


if this is due to environemnt variables? if yes, please help me know what variables to set here and how to set them? I checked various things and not sure where is API Key, access token, and all

**Comment by mahtin** [comment]
Please review the README file. You're answer is there.
