### ISSUE TITLE
Image error: /opt/local/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/tests/__init__.py

### ISSUE THREAD

**Issue by Schamschula** [cloudflare/python-cloudflare#178]
It looks like the tests directory wants to clobber existing files. After building version 2.15.0 under MacPorts, I get the following error while trying to activate the new package:

`
Error: Failed to activate py311-cloudflare: Image error: /opt/local/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/tests/__init__.py is being used by the active py311-utils port.  Please deactivate this port first, or use 'port -f activate py311-cloudflare' to force the activation.
`

I guess an easy workaround is to disable (delete in destroot) the tests directory for the time being.

**Comment by mahtin** [comment]
Dang. I use Brew on my Macs so this didn't show up. Dang. There's a bunch more tests added recently. But I think there's also a name conflict issue as `.../python3.11/site-packages/tests` maybe the wrong path. It's missing a `CloudFlare` element.

Can you check `2.14.3` also?

**Comment by Schamschula** [comment]
No such directory in `2.14.3`. I didn't see an error at the time I built and committed it.

**Comment by mahtin** [comment]
Good morning and Happy New Year. I see the issue and it was absolutely introduced (by mistake) in `2.15.0` (and still in `2.15.1`). I see exactly why it happened. A zero length file `__init__.py` was added to the `test` directory and that signaled the package to include `test` as a package - which is obviously wrong. This would have conflicted with ANY other Python package that already installed code in `.../lib/python3.11/site-packages/tests` folder on your system (or anyones system).

I'm preparing a release that fixes this and correctly places the test code in the right place (if you're going to have test code, then place it correctly!)

BTW: https://pypi.org/project/test/ does not exists - i.e no package has the name `test`, which means that some other package on your system has gone down this path and incorrectly installed a `test` folder. Wanna go look in your `/opt/local/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/tests/` folder and guess what package that is? (Maybe we can help them fix their code also?).

Stay tuned.

**Comment by mahtin** [comment]
Now fixed in `2.16.0` release. Please `pip install -U cloudflare` to do a clean install and confirm that this error has gone away. I'm still interested in knowing what's in your `/opt/local/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/tests/` folder!

**Comment by Schamschula** [comment]
Yes! The problem is gone!

See: https://github.com/macports/macports-ports/commit/a6bd6e8253990da5aa7fc106db4cc0bf04d9d1af

FYI Here's a listing of that folder

>  ls /opt/local/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/tests/
> __init__.py     bools_test.py   dicts           lists_test.py   objects_test.py
> __pycache__     dates_test.py   enum_test.py    math_test.py

These are files provided by the `utils` package https://pypi.org/project/utils/

**Comment by mahtin** [comment]
Most excellent news. 🎉

Plus, thanks for the folder listing ... I'll go check their source code (as it's the same issue I had with Cloudflare package).

**Comment by mahtin** [comment]
I see `1.0.2` pushed at https://pypi.org/project/utils/ now. I'd recommend upgrading, ie. `pip install -U utils` also. Their codebase is now fixed (my PR) and their `tests` folder removed.

**Comment by Schamschula** [comment]
Thanks for the heads up!
