### ISSUE TITLE
1012 Request must contain one of "purge_everything", "files", "tags", "hosts" or "prefixes"

### ISSUE THREAD

**Issue by roryabraham** [cloudflare/python-cloudflare#179]
We've started seeing a new error in [2.15.0](https://github.com/cloudflare/python-cloudflare/releases/tag/2.15.0):

```
cli4: /zones/:9ee042e6cfc7fd45e74aa7d2f78d617b/purge_cache - 1012 Request must contain one of "purge_everything", "files", "tags", "hosts" or "prefixes"
```

We have a number of examples of this in our GitHub actions, the most recent one being [here](https://github.com/Expensify/App/actions/runs/7350053573/job/20011063774). The command we're using has not changed for a long time:

```
cli4 --delete hosts='["staging.new.expensify.com"]' /zones/:9ee042e6cfc7fd45e74aa7d2f78d617b/purge_cache
```

We're tried with and without single quotes wrapping the array of hosts, and it does not seem to work. This appears to be a regression in the latest release of this package. Any ideas? Was there a breaking change we missed?

**Comment by roryabraham** [comment]
Confirmed, pinning to `2.14.3` solves the problem for us

**Comment by mahtin** [comment]
Two things going on here.

First. According to the API specs ... https://developers.cloudflare.com/api/operations/zone-purge ... you should be doing a `POST` operation as `DELETE` is not listed. I wonder if the backend always accepted `DELETE` as it's a somewhat obvious request method. That said, I tested this via the Python API and sure enough, it works. I would highly recommend you (at some point) move to a `POST` vs `DELETE` call.

However more importantly, yes, there's a bug in `2.15.0` within the `cli4` command. The API Python code works fine. I'm looking at the changed code and I think I see why. The tests are of the Python API and not the `cli4` command. That needs to change.

I'm very sorry this slipped out. (I saw your next message saying you fixed it via a 'pinned' install). I'll let you know when this is fixed.

**Comment by mahtin** [comment]
`2.15.1` released (and 2.15.0 has been yanked - for good reasons!). Please test and apologies again. I'm thinking thru test code as we speak. It was a stupid error to make its way out and so easy to test for.

**Comment by mahtin** [comment]
Just for the record:

The previous code ...
```
$ cli4 -V
Cloudflare library version: 2.15.0
$ cli4 --post purge_everything=True /zones/:$ZONE_NAME/purge_cache
cli4: /zones/:mahtin.net/purge_cache - 1012 Request must contain one of "purge_everything", "files", "tags", "hosts" or "prefixes"
$
```

The fix ...
```
$ pip install -U cloudflare
...
Installing collected packages: cloudflare
  Attempting uninstall: cloudflare
    Found existing installation: cloudflare 2.15.0
    Uninstalling cloudflare-2.15.0:
      Successfully uninstalled cloudflare-2.15.0
Successfully installed cloudflare-2.15.1
$
```

The fixed code ...
```
$ cli4 -V
Cloudflare library version: 2.15.1
$ cli4 --post purge_everything=True /zones/:$ZONE_NAME/purge_cache
{
    "id": "d8afaec3dd2b7f8c1b470e594a21a01d"
}
$
```

**Comment by roryabraham** [comment]
Wow, so cool to see that you fixed this so quickly. Thanks for the quick work. We'll update the version of this library that we're using and report back.

**Comment by mahtin** [comment]
Good morning and Happy New Year. Please let me know if this issue can be closed now? I believe it's fixed.

**Comment by roryabraham** [comment]
Yes, confirmed that this is fixed! Thanks again for the quick turnaround, and happy new year! 🎉
