### ISSUE TITLE
Change WAF Custom Rule with wrong position

### ISSUE THREAD

**Issue by r00t9** [cloudflare/python-cloudflare#180]
I try to update one rule but the index position is wrong. I get the info but in the information don't show any index.

I have this code 

```
rules = cf.zones.firewall.rules.get(zone_id)
....
# same changes in the code.. 
....
cf.zones.firewall.rules.put(zone_id, data=firewall_data)

```

**Comment by mahtin** [comment]
Sadly without much more information (i.e the actual `firewall_data` values), I can't exactly tell what your question is. It would seem that you're using the Python library calls correctly. If I guess correctly, you want to update the `index` value. That's a question that's outside of this libraries arena. 

A quick check and I see your point. I wrote this code:
```
    my_filter = {'expression': 'http.request.uri.path == "/private.html$"', 'paused': True, 'description': 'stop access to /private.html', 'ref': 'my_filter'}
    my_rule = {'action': 'block', 'filter': my_filter, 'paused': True}
    r = cf.zones.firewall.rules.post(zone_id, data=my_rule)
    if 'index' in r[0]:
        print(r[0]['index'])
```
If I run that code more than once, it returns an `index` value. Yet on the first call, it's not there. On the second call I get the value `2` and the third call I get `3`, etc etc. I don't know what you can do with `index` on a PUT call. Sorry.

But as I said, this is an API issue and not a Python library issue. Sorry. I think your issue should really be posted onto https://community.cloudflare.com/ as an API values question.
