### ISSUE TITLE
Get code and message from CloudFlare.exceptions.CloudFlareAPIError

### ISSUE THREAD

**Issue by ducphan30** [cloudflare/python-cloudflare#181]
Hello 🙂 

Hopefully I'm not wrong but it seems when we catch the `CloudFlare.exceptions.CloudFlareAPIError` exception, there is no way to retrieve the associated code and message returned by the API.

I'm working on load balancers in Cloudflare and when I try to delete an origin pool, it gives me an error when that pool is still being used (obviously...). This is what I'm trying to read from the above exception.

Code example:
```yaml

try:
    # delete the origin pool that is being used by a load balancer...

except CloudFlare.exceptions.CloudFlareAPIError as e:
    sys.exit(
        "/accounts/load_balancers/pools.delete %d %s - api call failed" % (e, e)
    )
```

The actual result of the above code is: 
`/accounts/load_balancers/pools.delete 412 HTTP response code 412 - api call failed`

When we enable the debug mode, we can see in the logs:

```

2024-01-18 22:03:14,433 Python Cloudflare API v4 DEBUG:Call: emulated curl command ...
       curl -X DELETE "https://api.cloudflare.com/client/v4/accounts/XXXXXXXX/load_balancers/pools/XXXXXXX" \
            -H "User-Agent: python-cloudflare/2.16.0/python-requests/2.31.0/python/3.11.7" \
            -H "Content-Type: application/json" \
            -H "Authorization: REDACTED" 
2024-01-18 22:03:14,805 - Python Cloudflare API v4 - DEBUG - Response: 412, application/json, b'{\n  "result": null,\n  "success": false,\n  "errors": [\n    {\n      "code": 1005,\n      "message": "Th'...
2024-01-18 22:03:14,805 Python Cloudflare API v4 DEBUG:Response: 412, application/json, b'{\n  "result": null,\n  "success": false,\n  "errors": [\n    {\n      "code": 1005,\n      "message": "Th'...
2024-01-18 22:03:14,806 - Python Cloudflare API v4 - DEBUG - Response: error 412 HTTP response code 412
2024-01-18 22:03:14,806 Python Cloudflare API v4 DEBUG:Response: error 412 HTTP response code 412
```

I guess the `message` (and `"code": 1005`) keys above in the `errors` list is:
_(copied from the Cloudflare UI)_
<img width="582" alt="image" src="https://github.com/cloudflare/python-cloudflare/assets/38530993/0eca40db-f72a-4727-90a0-0fc04610305f">

How can we retrieve them ?

Thanks !

**Comment by ducphan30** [comment]
Thanks for your reply.

I've read the documentation before opening this issue 😉 

Unfortunately, I think that for some specific API calls, the error messages management is not fully implemented as the above code snippet you wrote.

Example with this API call: https://developers.cloudflare.com/api/operations/account-load-balancer-pools-delete-pool

The returned message is `412 HTTP response code 412` when a pool is being used by another load balancer (with your code snippet).

**Comment by mahtin** [comment]
Ah ... `412` ... stay tuned! I'll look at it in a bit but I've seen this before.

**Comment by mahtin** [comment]
@ducphan30 - ok, I've replicated this and you are 100% correct. This wasn't coded fully and the error was not returned. I've written code that replaces this and with the updated code I now see the error message vs 412. I will craft a new release of the package today or tomorrow and message you here. Thank for you pointing this out. 

Just for the record, you can replicate this error via the following calls that create a pool, use it on a zone, then try to delete the pool before removing it from the zone. Once it's removed from the zone, you can delete the pool.
```
Create pool:
  /accounts/:account_id/load_balancers/pools POST
    Success
Create load balancer:
  /zones/:zone_id/load_balancers POST
    Success
Try to delete pool:
  /accounts/:account_id/load_balancers/pools DELETE
    Error expected: 1005 This object is referenced by other objects, delete them first.
Now remove pool from zone:
  /zones/:zone_id/load_balancers DELETE
    Success
Now delete pool:
  /accounts/:account_id/load_balancers/pools DELETE
    Success
```

**Comment by ducphan30** [comment]
Thanks for being reactive !

Please share with me the PR, thanks.

**Comment by mahtin** [comment]
@ducphan30 - please upgrade to `2.17.0`. It took a few edits to get this generically fixed; however, after testing a ton of API calls that produce `4xx` (ie. `421` and other `4xx` errors like `401` etc) I'm happy with this release. Your load balancer example now works correctly.

Please close the issue if you are happy with the release. Thanks.

**Comment by ducphan30** [comment]
Fixed !
Thanks a lot !
