### ISSUE TITLE
Would like to be able to pass in my own HTTP headers

### ISSUE THREAD

**Issue by securitypedant** [cloudflare/python-cloudflare#185]
Hi, i'm using this SDK for an internal project here at Cloudflare and have found this SDK super helpful. I wonder if you would be kind enough to add in some extra functionality.

My internal tool has no awareness of the authentication credentials for the API, instead, I am over-riding the 'base_url' to point to another service here in Cloudflare that will proxy my request and add API credentials for the account.

In my code, I want to add the following HTTP headers to every API call your SDK makes.

``` python
additional_headers = {
            'CF-Access-Client-Id': os.getenv('CF-Access-Client-Id'),
            'CF-Access-Client-Secret': os.getenv('CF-Access-Client-Secret'),
            'CML-Account-Id': account_id
        }
```
        
Could you add a public method on the Cloudflare class that would allow me to add these?

**Comment by securitypedant** [comment]
I was trying to figure out how to do this myself and submit a PR, but on line 137 of cloudflare.py it states...

``` python
def do_auth(self, method, parts, identifiers, params=None, data=None, files=None):
            """ Cloudflare v4 API"""

            headers = {}
            self._add_headers(headers)
            self._add_auth_headers(headers, method)
```

and i'm unsure what the best practice would be. Do I remove the headers = {} and instead pass in the additional headers into the do_auth()?

**Comment by mahtin** [comment]
This is a good idea; however, would you mind if I implemented this as a generic header addition method? (i.e. Any header vs your specific ones).

While this could be dangerous (send a wrong `Keep-Alive` and `requests` will barf) that's the nature of a low-level option like this! Caveat Emptor!

**Comment by securitypedant** [comment]
Absolutely! Whatever method you feel is appropriate to achieve my goal and support others...

**Comment by mahtin** [comment]
Now published as `2.19.2`. A simple `pip install --upgrade cloudflare` will work. Instructions in README (which is the same as above).

**Comment by securitypedant** [comment]
Wow Martin, that's superb. I will be implementing this new version into my project tomorrow. Thank you so much for such a quick turnaround!

**Comment by securitypedant** [comment]
What's the protocol here? Do I close the issue? Need me to test and report back first?

**Comment by mahtin** [comment]
Test away tomorrow ... close when you're happy. Comment if you're not happy! 😳

**Comment by mahtin** [comment]
@securitypedant - all good?

**Comment by securitypedant** [comment]
Sorry Martin, stuck problem solving a related piece of code... not actually got the entire thing working yet. Will report back as soon as I have a solid test complete.

**Comment by securitypedant** [comment]
Finally got the integration working, and it does exactly what I need. Thank you so much Martin! This was a big win.
