### ISSUE TITLE
Possible error in README example

### ISSUE THREAD

**Issue by Ali-Flt** [cloudflare/python-cloudflare#193]
In this readme example:
```python
#!/usr/bin/env python

import sys
import CloudFlare

def main():
    zone_name = sys.argv[1]
    cf = CloudFlare.CloudFlare()
    zone_info = cf.zones.get(params={'name': zone_name})
    zone_id = zone_info['id']

    dns_name = sys.argv[2]
    dns_records = cf.zones.dns_records.get(zone_id, params={'name':dns_name + '.' + zone_name})
    for dns_record in dns_records:
        dns_record_id = dns_record['id']
        r = cf.zones.dns_records.delete(zone_id, dns_record_id)
    exit(0)

if __name__ == '__main__':
    main()
```
`zone_info = cf.zones.get(params={'name': zone_name})` returns a list. So I believe `zone_id = zone_info[0]['id']` is correct.

**Comment by mahtin** [comment]
Thank you! This is a typo and `zone_id = zone_info[0]['id']` is correct. It will get edited into the next release. Thank you.

**Comment by mahtin** [comment]
A quick update to GitHub's README is pushed - however, this won't show up on PyPI until a full release is done. Thank you for seeing this (it's clearly been there for ages!).
