### ISSUE TITLE
ModuleNotFoundError: No module named 'CloudFlare' after cloudflare dependency update

### ISSUE THREAD

**Issue by clarkohw** [cloudflare/python-cloudflare#194]
Opening this issue in case anyone else runs into it:
in my code I use a statement like this:
```
import CloudFlare
```

previously it was working in my CI setup, but I'm guessing at some point this library changed the dependent version of the `cloudflare` package from 2.* to 3.* as a result I started this error:

```
ModuleNotFoundError: No module named 'CloudFlare' 
```

To fix the issue I pinned both `python-cloudflare` and `cloudflare` in my `requirements.txt`

**Comment by mahtin** [comment]
Correct. Sorry for the inconvenience. 

Please read the README warnings at https://github.com/cloudflare/python-cloudflare plus, you should have received an email about this. Pinning is the correct answer.
