### ISSUE TITLE
Inconsistent encoding between zone name and dns_records name for internationalized domains

### ISSUE THREAD

**Issue by FutureSharks** [cloudflare/python-cloudflare#22]
Hi,
Take a look at this:
```
>>> my_domain = cf.zones.get(params = { 'name': 'xn--sanremomlheim-3ob.de' })
>>> my_domain[0]['name']
u'sanremom\u0102\u017alheim.de'
>>> my_domain = cf.zones.get(params = { 'name': 'sanremomülheim.de' })
>>> my_domain[0]['name']
u'sanremom\u0102\u017alheim.de'
>>> dns_records = cf.zones.dns_records.get(my_domain[0]['id'])
>>> dns_records[0]['name']
u'www.sanremom\xfclheim.de'
>>> print my_domain[0]['name']
sanremomĂźlheim.de
>>> print dns_records[0]['name']
www.sanremomülheim.de
```

The way the domain name is represented is different, `sanremom\xfclheim.de` vs `sanremom\u0102\u017alheim.de`.

Is this a bug?

How could I test if `my_domain[0]['name']` is in `dns_records[0]['name'] ` in python?

Thanks,
Max

**Comment by mahtin** [comment]
@FutureSharks - oops! Normally I would say there's some code you need to dig up in order to make punycode and domain names work cleanly together. Python does a so-so job at doing this.

You are correct that ```xn--sanremomlheim-3ob.de``` is ```sanremomülheim.de```.  However ```sanremom\u0102\u017alheim.de``` as you say is ```sanremomĂźlheim.de``` which is clearly wrong. 

Off to debug ... more later!

**Comment by mahtin** [comment]
@FutureSharks - I've created an internal ticket to address this. The ```name``` value in the response from a ```/zones``` API call is wrong. The ```zone_name``` value in the response from a ```/zones/:id/dns_records``` API call is correct. This should work for you ...
```
>>>print dos_records[0]['zone_name']
www.sanremomülheim.de
```
I'll update you when there's a change to the API calls.

In other news. The cli4 command also had a small python bug that stopped it working with IDNs. If you grab the latest from github (or pip version 1.4.11 or above) you will be able to test this on the command line.
```
$ cli4 /zones/:sanremomülheim.de
...
$
$ cli4 /zones/:sanremomülheim.de/dns_records
...
$
```

**Comment by FutureSharks** [comment]
OK great, thanks for the update, mahtin.

**Comment by mahtin** [comment]
@FutureSharks - well it's been a long time and I've finally squashed the unicode bugs. I've also made the library python2/python3 compatible. Both the ```cli4``` command and the libraries now do the right thing.  This was purely an issue with strings and unicode and python2/python3 json. Here's my test zone and your example from above.

```
$ python3
Python 3.5.2 (default, Oct 11 2016, 05:05:28) 
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.38)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>>
>>> import CloudFlare
>>> cf = CloudFlare.CloudFlare()
>>> my_domain = cf.zones.get(params = { 'name': 'übergrösse.space' })
>>> my_domain[0]['name']
'übergrösse.space'
>>> dns_records = cf.zones.dns_records.get(my_domain[0]['id'])
>>> dns_records[0]['name']
'www.übergrösse.space'
>>> print(my_domain[0]['name'])
übergrösse.space
>>> print(dns_records[0]['name'])
www.übergrösse.space
>>>
>>>
>>> 
>>> my_domain = cf.zones.get(params = { 'name': 'xn--bergrsse-r4a8c.space' })
>>> my_domain[0]['name']
'übergrösse.space'
>>> dns_records = cf.zones.dns_records.get(my_domain[0]['id'])
>>> dns_records[0]['name']
'www.übergrösse.space'
>>> print(my_domain[0]['name'])
übergrösse.space
>>> print(dns_records[0]['name'])
www.übergrösse.space
>>>
>>> exit()
$
```
This is now pushed to [GitHub](https://github.com/cloudflare/python-cloudflare) and [PyPI](https://pypi.python.org/pypi/cloudflare) as version 2.0.4.

Please test and hopefully you this is acceptable.
