### ISSUE TITLE
Modify WAF rules

### ISSUE THREAD

**Issue by Sarga** [cloudflare/python-cloudflare#23]
Hello.

Could you please help me?
How I can change settings for waf rules via cli4?

For example I need to change
`curl -X PATCH "https://api.cloudflare.com/client/v4/zones/$zone_id/firewall/waf/packages/1e334934fd7ae32ad705667f8c1057aa/rules/100047WP" -H "Content-Type:application/json" -H "X-Auth-Key:$token" -H "X-Auth-Email:$login" --data '{"mode":"challenge"}'`

Via cli4 it doesn't work :(
`cli4 --patch mode=challenge /zones/:example.com/firewall/waf/packages/:1e334934fd7ae32ad705667f8c1057aa/rules/100047WP`

Thank you for your work.

**Comment by mahtin** [comment]
@Sarga - oh; this is actually a complete oversight of the core code within the ```_raw``` library call.
```
def _raw(self, method, headers,
         api_call_part1, api_call_part2=None, api_call_part3=None,
         identifier1=None, identifier2=None,
         params=None, data=None):
    ...
    url = (self.base_url + '/'
           + api_call_part1 + '/'
           + identifier1 + '/'
           + api_call_part2 + '/'
           + identifier2)
    ...
```
As you can see, there's no ability to handle a third ```identifier``` within an API call. This is an oversight that was introduced with the new API waf calls.

It's only affects the following API calls (which is the ones you are using):
```
 GET   /zones/:zone_identifier/firewall/waf/packages/:package_identifier/groups/:identifier
 PATCH /zones/:zone_identifier/firewall/waf/packages/:package_identifier/groups/:identifier
 GET   /zones/:zone_identifier/firewall/waf/packages/:package_identifier/rules/:identifier
 PATCH /zones/:zone_identifier/firewall/waf/packages/:package_identifier/rules/:identifier
```
Code will have to be written, both in ``cli4`` and the core libraries. Maybe later today.

**Comment by mahtin** [comment]
@Sarga - the code is now there. It's in the 1.4.8 release (and pushed to pip). The cli4 command works along with the python api code. The third identifier is passed via the api call just like the first two.
```
$ cli4 --get /zones/:example.com/firewall/waf/packages/:1e334934fd7ae32ad705667f8c1057aa/rules/:100008C
{
    "allowed_modes": [
        "default", 
        "disable", 
        "simulate", 
        "block", 
        "challenge"
    ], 
    "default_mode": "block", 
    "description": "Block SQLi sleep probing", 
    "group": {
        "id": "f90712123fb02287348dd34c0a282bb9", 
        "name": "Cloudflare Specials"
    }, 
    "id": "100008C", 
    "mode": "default", 
    "package_id": "1e334934fd7ae32ad705667f8c1057aa", 
    "priority": "22"
}
$
```
Please confirm on your side and then you can close this issue.

**Comment by Sarga** [comment]
cli4 --get /zones/:example/firewall/waf/packages/:1e334934fd7ae32ad705667f8c1057aa/rules/:100008C  - works well

cli4 --get /zones/:example.com/firewall/waf/packages/:1e334934fd7ae32ad705667f8c1057aa/rules/:100047WP - :NOT CODED YET 3

@mahtin check it please.

Also could you please add http2 / pseudo ipv4 settings?
https://github.com/cloudflare/python-cloudflare/pull/25

**Comment by mahtin** [comment]
Yup - typo on my part. I matched ```[A-F]``` vs. ```[A-Z]``` (I just had a hexadecimal moment). This is now pushed to git and pip (as version 1.4.10).
```
$ cli4 --get /zones/:example.com/firewall/waf/packages/:1e334934fd7ae32ad705667f8c1057aa/rules/:100047WP 
{
    "allowed_modes": [
        "default", 
        "disable", 
        "simulate", 
        "block", 
        "challenge"
    ], 
    "default_mode": "disable", 
    "description": "Block WordPress User-Agent completely (Pingback attack)", 
    "group": {
        "id": "f90712123fb02287348dd34c0a282bb9", 
        "name": "Cloudflare Specials"
    }, 
    "id": "100047WP", 
    "mode": "default", 
    "package_id": "1e334934fd7ae32ad705667f8c1057aa", 
    "priority": "97"
}
$
```
Sorry for the extra cycle. Glad you are using the Python libs.
