### ISSUE TITLE
Add support zone blacklist

### ISSUE THREAD

**Issue by MaximKiselev** [cloudflare/python-cloudflare#27]
yep

**Comment by mahtin** [comment]
Do you mean **Access Rules** settings? These can be managed at an IP, IP block, ASN or country level? For example, here's a way to list your existing access rules:
```
$ cli4 /zones/:example.com/firewall/access_rules/rules | \
  jq -c '.[]|{"id":.id,"status":.status,"mode":.mode,"configuration":.configuration}'
{"id":"da6448847c5d18247184295eed1f5d8b","status":"active","mode":"whitelist","configuration":{"target":"ip","value":"127.0.0.1"}}
...
$ 
```
Here's an example of adding an IP range and marking it to block (be careful as you can block the wrong thing).
```
$ cli4 --post \
       mode='block' \
       notes='reason is clear' \
       configuration='{ "value": "2001:db8::/32", "target": "ip_range" }' \
       scope='{ "type": "zone" }' \
       /zones/:example.com/firewall/access_rules/rules | \
  jq -c '{"id":.id,"status":.status}'
{"id":"00000000000000000000000000000000","status":"active"}
$
```
This is the same as using https://www.cloudflare.com/a/firewall/example.com/ip_firewall on the customer control panel.

The same can be done via Python.

Does that help with your question?

**Comment by MaximKiselev** [comment]
hi, no. access rule is cool thing, but i am say about a domains blacklist.  For example, if domain in the blacklist api raises Exception, but i do not check domain without adding(is not good because more queries x2). Is it possible? Thanks

**Comment by mahtin** [comment]
There should only be one query required to add a zone. Here's an example of a **banned** domain name (well **blacklisted** for obvious reasons). 
```
$ cli4 --post name='google.com' jump_start=false /zones/
cli4: /zones - 1097 This zone is banned and cannot be added to CloudFlare at this time, please contact CloudFlare Support.
$
```
The jump_start flag can be used to stop the DNS zone scanning; which maybe useful in some cases.

There's no call to check if a zone is banned. That test is only done when you want to add a zone to your account.

Does this help?

**Comment by MaximKiselev** [comment]
>cf.zones.post(data={'jump_start':False, 'name': zone_name})
@mahtin , yes.  but this request add domain in panel. What's about if i don't want to add domain?

**Comment by mahtin** [comment]
Maxim,

> What's about if i don't want to add domain?

There's no way to do that; the checks are done when you add a zone. You can (of course) delete the zone right afterwards; but I would not really recommend that method. 

The good part is that I now understand your issue. It's more a generic Cloudflare issue vs. a Python library issue.

> Does he use local blacklist database?(backend cloudflare)

There's a myriad of tests that are performed during the process of adding a zone.

As I said above; I would recommend you move this issue over to https://support.cloudflare.com/ as this isn't a Python specific issue.
