### ISSUE TITLE
"logger" isn't an actual requirement

### ISSUE THREAD

**Issue by ross** [cloudflare/python-cloudflare#30]
Went to install the CloudFlare python library and was surprised it was [pulling in a module for logging](https://github.com/cloudflare/python-cloudflare/blob/5358208360c891cdabb954ba85c8ea269891a350/setup.py#L35) called `logger`. Looked through the CF code and as best as i can tell it's not importing `logger` anywhere, which is good b/c that module as a single .py and config file with the following which would mess up the logging config for most anything utilizing logging.

```
import logging
import logging.config
import os
import sys
import types

logging.getLogger('paramiko').setLevel(logging.WARNING)
logging.getLogger('requests').setLevel(logging.WARNING)

config_file = os.path.join(os.path.dirname(__file__), 'logging.conf')

logging.config.fileConfig(config_file, disable_existing_loggers=False)
logger = logging.getLogger()


def error(self, msg, *args, **kwargs):
    self.error(msg, *args, **kwargs)
    sys.exit(1)

logger.interrupt = types.MethodType(error, logger)
logger.info = logger.info
logger.warn = logger.warn
``` 

Pretty sure that line should just be dropped from the requirements list since everything being used is part of the stdlib.

**Comment by mahtin** [comment]
Correct. I fixed this (and removed some of the confusion) in ```1.6.2``` and pushed to [pypi](https://pypi.python.org/pypi/cloudflare/1.6.2).
