### ISSUE TITLE
Bug in example

### ISSUE THREAD

**Issue by nordicdyno** [cloudflare/python-cloudflare#31]
https://github.com/cloudflare/python-cloudflare/blob/master/examples/example_paging_thru_zones.py#L13

here should be:
`page_number = 1`

proof: https://api.cloudflare.com/#zone-list-zones

**Comment by mahtin** [comment]
Correct - this was fixed in this [commit](https://github.com/cloudflare/python-cloudflare/commit/fb12f3000824051d34008a2c63e9eabce0822edc). Sorry about that.
