### ISSUE TITLE
Example for deleting DNS record

### ISSUE THREAD

**Issue by iMerica** [cloudflare/python-cloudflare#33]
Hi,

Can you please provide an example of how to delete a specific DNS record (like a CNAME) from a given zone?

I checked the examples directory, the README and read the code, but I'm still not absolutely certain how this is done.  Getting this wrong could mean accidentally deleting the entire zone instead of a specific DNS record so any help with this would be super appreciated.

Thanks,

Michael

**Comment by iMerica** [comment]
For anyone else not willing to risk deleting their entire zone using `python-cloudflare`, this is how I got around it

```python
import requests

# First get zone_id and record_id using the official python api client.
# Then use Requests to delete the record.
headers = {
    'X-Auth-Email': CLOUDFLARE_EMAIL_ADDRESS,
    'X-Auth-Key': CLOUDFLARE_API_KEY,
    'Content-Type': 'application/json'
}
cloudinary_base_url = 'https://api.cloudflare.com/client/v4/zones/'
url = "{0}/{1}/dns_records/{2}".format(cloudinary_base_url, zone_id, record_id)
response = requests.delete(url, headers=headers)

```

**Comment by niamster** [comment]
@iMerica if you check out the [implementation](https://github.com/cloudflare/python-cloudflare/blob/37ddc7eea035b5629d5ec7e09ea6020c4c5520ff/CloudFlare/cloudflare.py#L54) you would find that you can delete a dns record as:
```python
cf.zones.dns_records.delete(zone['id'], identifier2=record['id'])
# or simply
cf.zones.dns_records.delete(zone['id'], record['id'])
```

**Comment by iMerica** [comment]
Thanks @niamster 👍

**Comment by alexvicegrab** [comment]
Works great, would be great if this brief example could be added on the README.md :)

**Comment by mahtin** [comment]
@iMerica - the ```cf.zones.dns_records.delete(zone_id, dns_record_id)``` call will only delete a specific DNS record (and not the zone). Both the ```zone_id``` and ```dns_record_id``` need to be correct before anything happens. See the specific API [documentation](https://api.cloudflare.com/#dns-records-for-a-zone-delete-dns-record).

I've added a very simple example in both the examples folder and in the README in this [commit](https://github.com/cloudflare/python-cloudflare/commit/90e3ea57e473b2cf332b7cc5ed22d5bf66ffe36a).
