### ISSUE TITLE
Regression in 1.7.0 when adding TXT records

### ISSUE THREAD

**Issue by multippt** [cloudflare/python-cloudflare#36]
* Expected result: Either a successful or "record already exists" result from API, as seen from version 1.6.2.
* Instead got error: CloudFlare.exceptions.CloudFlareAPIError: DNS Validation Error, on version 1.7.0

Sample code to reproduce (replace relevant parts)
```
import CloudFlare
cf = CloudFlare.CloudFlare("[email]", "[key]")
zones = cf.zones.get(params={'name': "[domain]",'per_page': 1})
zone_id = zones[0]["id"]
print(cf.zones.dns_records.post(zone_id, data={'type': 'TXT', 'name': 'testtxt', 'content': 'test', 'ttl': 120}))
```

This bug will affect services that make use of TXT records (e.g. LetsEncrypt) when using the latest version of the Cloudflare module

**Comment by mahtin** [comment]
Yes - typo left over from testing. So sorry about that. I've pushed 1.7.1 with the [one line fix](https://github.com/cloudflare/python-cloudflare/commit/d4434106da68ef1828caaf49e8a25c442bb2dba2).
