### ISSUE TITLE
"put" not available for dns_records

### ISSUE THREAD

**Issue by benkoller** [cloudflare/python-cloudflare#40]
Hi,

the readme states that put is available for `dns_records`-operations:

GET | PUT | POST | PATCH | DELETE | API call
-- | -- | -- | -- | -- | --
(...) | (...) | (...) | (...) | (...) | (...)
`GET` | `PUT` | `POST` |   | `DELETE` | /zones/:identifier/dns_records
(...) | (...) | (...) | (...) | (...) | (...)

However when using `dns_records.put()` (`cf.zones.dns_records.put(zone_id, data=record)`) the SDK throws an error: `CloudFlare.exceptions.CloudFlareAPIError: Method PUT not available for that URI.`

At least the readme should be correct about the available methods, but ideally an idempotent `PUT` should be available for `dns_records` to avoid duplicate records.

**Comment by mahtin** [comment]
See https://github.com/cloudflare/python-cloudflare/blob/master/examples/example_update_dynamic_dns.py for an example. It needs an extra argument.

**Comment by mahtin** [comment]
For PUT you can see this example https://github.com/cloudflare/python-cloudflare/blob/master/examples/example_create_zone_and_populate.py

**Comment by benkoller** [comment]
Thx for the links, thats indeed pretty helpful 👍
