### ISSUE TITLE
Unable to pull ELS schema fields via cli4

### ISSUE THREAD

**Issue by thatChadM** [cloudflare/python-cloudflare#41]
Per https://support.cloudflare.com/hc/en-us/articles/115003165991-Enterprise-Log-Share-ELS-Migrating-to-New-Endpoint, I should be able to pull down the list of defined fields for the received-time-ordered logs via cli4 --get /zones/:zone_id/logs/received/fields, but no go.  I've even added the path entries to .cloudflare/cloudflare.cfg, and still no go.  Initial error was "/zones/:zone_id/logs - not found", now I get "/zones/:zone_id/logs/received - not found".

**Comment by elithrar** [comment]
Hi @thatChadM - can you provide more details? 

e.g. What is the path you're hitting, and are you using an Enterprise zone w/ Enterprise Log Share enabled? Fetching from these endpoints will not work otherwise, beyond any potential issues with this library.

**Comment by thatChadM** [comment]
Howdy @elithrar 
!
Yep, ELS is enabled and I'm working with enterprise zones.

Expected form fails:
> cli4 --get /zones/:5367f21a3236d12599493ea4b0130697/logs/received/fields
cli4: /zones/:5367f21a3236d12599493ea4b0130697/logs/received - not found

Drop the leading : since the zone id is given directly to match curl, still fails but with different error:
> cli4 --get /zones/5367f21a3236d12599493ea4b0130697/logs/received/fields
cli4: /zones/5367f21a3236d12599493ea4b0130697 - not found

And last, curl, which works:
> curl -H 'X-Auth-Email: <email>' -H 'X-Auth-Key: <key>' https://api.cloudflare.com/client/v4/zones/5367f21a3236d12599493ea4b0130697/logs/received/fields
{"CacheCacheStatus":"unknown | miss | expired | updating | stale | hit | ignored | bypass | revalidated","CacheResponseBytes":"Number of bytes returned by the cache","CacheResponseStatus":"HTTP status code returned by the cache to the edge: all requests (including non-cacheable ones) go through the cache: also see CacheStatus field","ClientASN":"Client AS number","ClientCountry":"Country of the client IP address","ClientDeviceType":"Client device type","ClientIP":"IP address of the client","ClientIPClass":"Client IP class","ClientRequestBytes":"Number of bytes in the client request","ClientRequestHost":"Host requested by the client","ClientRequestMethod":"HTTP method of client request","ClientRequestProtocol":"HTTP protocol of client request","ClientRequestReferer":"HTTP request referrer","ClientRequestURI":"URI requested by the client","ClientRequestUserAgent":"User agent reported by the client","ClientSSLCipher":"Client SSL cipher","ClientSSLProtocol":"Client SSL protocol","ClientSrcPort":"Client source port","EdgeColoID":"Cloudflare edge colo id","EdgeEndTimestamp":"Unix nanosecond timestamp the edge finished sending response to the client","EdgePathingStatus":"Edge pathing status","EdgeResponseBytes":"Number of bytes returned by the edge to the client","EdgeResponseCompressionRatio":"Edge response compression ratio","EdgeResponseStatus":"HTTP status code returned by Cloudflare to the client","EdgeStartTimestamp":"Unix nanosecond timestamp the edge received request from the client","OriginIP":"IP of the origin server","OriginResponseBytes":"Number of bytes returned by the origin server","OriginResponseHTTPExpires":"Value of the origin 'expires' header in RFC1123 format","OriginResponseHTTPLastModified":"Value of the origin 'last-modified' header in RFC1123 format","OriginResponseStatus":"Status returned by the origin server","OriginResponseTime":"Number of nanoseconds it took the origin to return the response to edge","RayID":"Ray ID of the request","WAFAction":"Action taken by the WAF, if triggered","WAFRuleID":"ID of the applied WAF rule","ZoneID":"Internal zone ID"}


curl & cli4 paths are effectively the same from /zones, the only real difference is cli4 needs the preceding : for either the zone name or zone id, while curl does not want the : and will only work with the zone id.

**Comment by elithrar** [comment]
cli4 is looking for a Result object (array) in the response, and our log
endpoints provide logs in NDJSON (the logs themselves) or as a flat object
(the field output). Martin, the maintainer, is looking at options to
resolve this.

In the meantime you can use https://github.com/cloudflare/logshare to pull
logs: there are pre-built binaries, so you don’t need Go installed to use
it.

**Comment by mahtin** [comment]
Hello @thatChadM,

The ``cli4`` command uses : to introduce elements that need processing. In the [README](https://github.com/cloudflare/python-cloudflare/blob/master/README.md) file, this is described within some of the examples.

You were doing this correctly; however, the ``/zones/:zone_id/logs/received`` & ``/zones/:zone_id/logs/received/fields`` API calls don't return data in the same format as the existing v4 calls. This causes ``cli4`` (actually the underlying libraries) to fail when parsing the returned JSON. This is not good. Code needs to be written in order to address this. I will do that soon.

As a side note, your effort to add these API calls via ``$HOME/.cloudflare/cloudflare.cfg`` would have the same issue. The return values would cause the underlying libraries to raise an error.

**Comment by thatChadM** [comment]
Just to be clear, I am not trying to use cli4 to pull the logs themselves, just the field definitions.  I already have a tool to pull the logs via curl.  I simply tried to use cli4 to grab the field defs because it far faster to use cli4 than copying & pasting the assorted curl options to do it.

Why can't the back end that responds to /logs/received/fields simply return them in a Result array?

Ahh... and this also explains why when I process via curl & jq I have to start the jq filter with .request[], but not when using cli4.  I was vaguely curious about the difference but never bothered to investigate further.

**Comment by mahtin** [comment]
@thatChadM - you've hit the nail on the head. The ``/zones/:zone_id/logs/received`` & ``/zones/:zone_id/logs/received/fields`` API calls didn't implement the ``result[]`` JSON structure (or any of the other v4 structure; which is why cli4 and the underlying python libraries raise an error. This is a mistake.

I'm looking at adding code to the underlying libraries to handle this that doesn't look like a hack. So far, I have working code, but it's pretty ugly!

**Comment by mahtin** [comment]
@thatChadM - one other point. Yes, the ``cli4`` command is meant to unwrap the returned data from an API call and provide the answers (vs the returned structure which includes error messages, paging, etc). It's mean to make it easy to interact with the Cloudflare API and replace ``curl`` calls.

**Comment by mahtin** [comment]
A fix for this is now pushed to [GitHub](https://github.com/cloudflare/python-cloudflare) and [PyPI](https://pypi.python.org/pypi/cloudflare) as version 2.0.4. It handles the non-standard response type for the ```/zones/:zone_id/logs/received``` & ```/zones/:zone_id/logs/received/fields``` API calls. For example:

```
$ cli4 /zones/:example.com/logs/received/fields
{
    "CacheCacheStatus": "unknown | miss | expired | updating | stale | hit | ignored | bypass | revalidated", 
    "CacheResponseBytes": "Number of bytes returned by the cache", 
    "CacheResponseStatus": "HTTP status code returned by the cache to the edge: all requests (including non-cacheable ones) go through the cache: also see CacheStatus field", 
    "ClientASN": "Client AS number", 
    "ClientCountry": "Country of the client IP address", 
    "ClientDeviceType": "Client device type", 
    "ClientIP": "IP address of the client", 
    "ClientIPClass": "Client IP class", 
    "ClientRequestBytes": "Number of bytes in the client request", 
    "ClientRequestHost": "Host requested by the client", 
    "ClientRequestMethod": "HTTP method of client request", 
    "ClientRequestProtocol": "HTTP protocol of client request", 
    "ClientRequestReferer": "HTTP request referrer", 
    "ClientRequestURI": "URI requested by the client", 
    "ClientRequestUserAgent": "User agent reported by the client", 
    "ClientSSLCipher": "Client SSL cipher", 
    "ClientSSLProtocol": "Client SSL protocol", 
    "ClientSrcPort": "Client source port", 
    "EdgeColoID": "Cloudflare edge colo id", 
    "EdgeEndTimestamp": "Unix nanosecond timestamp the edge finished sending response to the client", 
    "EdgePathingOp": "Indicates what type of response was issued for this request (unknown = no specific action)", 
    "EdgePathingSrc": "Details how the request was classified based on security checks (unknown = no specific classification)", 
    "EdgePathingStatus": "Indicates what data was used to determine the handling of this request (unknown = no data)", 
    "EdgeResponseBytes": "Number of bytes returned by the edge to the client", 
    "EdgeResponseCompressionRatio": "Edge response compression ratio", 
    "EdgeResponseStatus": "HTTP status code returned by Cloudflare to the client", 
    "EdgeStartTimestamp": "Unix nanosecond timestamp the edge received request from the client", 
    "OriginIP": "IP of the origin server", 
    "OriginResponseBytes": "Number of bytes returned by the origin server", 
    "OriginResponseHTTPExpires": "Value of the origin 'expires' header in RFC1123 format", 
    "OriginResponseHTTPLastModified": "Value of the origin 'last-modified' header in RFC1123 format", 
    "OriginResponseStatus": "Status returned by the origin server", 
    "OriginResponseTime": "Number of nanoseconds it took the origin to return the response to edge", 
    "RayID": "Ray ID of the request", 
    "SecurityLevel": "The security level configured at the time of this request. This is used to determine the sensitivity of the IP Reputation system.", 
    "WAFAction": "Action taken by the WAF, if triggered", 
    "WAFFlags": "Additional configuration flags: simulate (0x1) | null", 
    "WAFMatchedVar": "The full name of the most-recently matched variable", 
    "WAFProfile": "WAF profile: low | med | high", 
    "WAFRuleID": "ID of the applied WAF rule", 
    "WAFRuleMessage": "Rule message associated with the triggered rule", 
    "ZoneID": "Internal zone ID"
}
$
```

Here's a sample call, which would return data if processed on an Enterprise zone.

```
$ cli4 start=2018-02-14T00:00:00Z end=2018-02-15T00:00:00Z sample=0.001 /zones/:example.com/logs/received
{
    "result": null, 
    "success": true
}
$
```
