### ISSUE TITLE
Unable to delete record, always connection failed, how to resolve it, thanks very much

### ISSUE THREAD

**Issue by Isites** [cloudflare/python-cloudflare#43]
![problem](https://user-images.githubusercontent.com/8931156/35037754-6551192e-fbb3-11e7-862a-11d4668801c2.png)

**Comment by mahtin** [comment]
@lziest - Please see the example [example_delete_zone_entry.py](https://github.com/cloudflare/python-cloudflare/blob/master/examples/example_delete_zone_entry.py) as this is working code.

```
    for dns_record in dns_records:
        dns_record_id = dns_record['id']
        dns_record_name = dns_record['name']
        dns_record_type = dns_record['type']
        dns_record_value = dns_record['content']
        print 'DNS RECORD:', dns_record_id, dns_record_name, dns_record_type, dns_record_value

        try:
            dns_record = cf.zones.dns_records.delete(zone_id, dns_record_id)
            print 'DELETED'
        except CloudFlare.exceptions.CloudFlareAPIError as e:
            exit('/zones.dns_records.delete %s - %d %s - api call failed' % (dns_name, e, e))
```

This code works. First export zone contents.

```
$ ./example_dns_export.py obfuscated-example.com | fgrep record 
record4.obfuscated-example.com. 300     IN      TXT     "some text"
record3.obfuscated-example.com. 300     IN      CNAME   record1.obfuscated-example.com.
record1.obfuscated-example.com. 300     IN      A       10.0.0.1
record2.obfuscated-example.com. 300     IN      AAAA    2001:d8b::2
$
```
Then delete one record (see source code in examples folder).
```
$ ./example_delete_zone_entry.py obfuscated-example.com record2
ZONE: 12345678901234567890123456789012 obfuscated-example.com
DNS RECORD: 12345678901234567890123456789012 record2.obfuscated-example.com AAAA 2001:d8b::2
DELETED
$
```
Then export zone again to see it gone.
```
$ ./example_dns_export.py obfuscated-example.com | fgrep record
record4.obfuscated-example.com. 300     IN      TXT     "some text"
record3.obfuscated-example.com. 300     IN      CNAME   record1.obfuscated-example.com.
record1.obfuscated-example.com. 300     IN      A       10.0.0.1
$
```

I hope this helps.

**Comment by mahtin** [comment]
@lziest - after looking at your code, I think you have a Python issue. Your ``cf`` variable maybe unset when you get to your ``delete`` code.

**Comment by lziest** [comment]
@Isites please see above.

**Comment by mahtin** [comment]
@lziest - apologies (blame it on early-morning pre-cafine typing). :)

**Comment by Isites** [comment]
@lziest I have solved this problem. Is there a bug here. Because I changed the source of `cloudflare.py`.  The change is to change the variable `json` to `data`, Then, successed
![problem](https://user-images.githubusercontent.com/8931156/35372256-da07ae1a-01d3-11e8-98bd-56602c23ed7f.png)

**Comment by mahtin** [comment]
Please let me know what version number if requests you are using?

**Comment by Isites** [comment]
The version is `2.2.1`
![image](https://user-images.githubusercontent.com/8931156/35422552-3ed2d378-0284-11e8-9de0-841bc66ad4a7.png)

**Comment by mahtin** [comment]
@Isites - yup; I see an issue here!
```
$ python
Python 2.7.10 (default, Feb  7 2017, 00:08:15) 
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import requests
>>> print(requests.__version__)
2.18.4
>>> ^D
$
```

```
$ python3
Python 3.5.2 (default, Oct 11 2016, 05:05:28) 
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.38)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import requests
>>> print(requests.__version__)
2.12.1
>>> 
$
```
I see some other issues as a move forward with checking newer versions of both ``request()`` and ``python3``. Just building a new testing setup and then I'm ready to resolve this. If done correctly, then it should work for both versions of python along with newer and older ``requests()``.

**Comment by mahtin** [comment]
@Isites - I reread your previous note. Your version of ``requests()`` is too old and that's why you are seeing this error. See http://docs.python-requests.org/en/latest/community/updates/#software-updates and scroll down a long way ...
```
2.4.2 (2014-10-05)
Improvements
* FINALLY! Add json parameter for uploads! (#2258)
* Support for bytestring URLs on Python 3.x (#2238)
``
I think this is not worth coding around. However, I will choose a required minimum version number for that library. There's a lot of fixes that are needed in that library.
