### ISSUE TITLE
Error trying to change zone setting "always_use_https"

### ISSUE THREAD

**Issue by gonguinguen** [cloudflare/python-cloudflare#45]
I can successfully change other similar zone settings, like "automatic_https_rewrites", and it works perfectly, however when I try to change "always_use_https" I receive this error:

`Traceback (most recent call last):
  File "/home/gonguinguen/medios/gluon/restricted.py", line 227, in restricted
    exec ccode in environment
  File "/home/gonguinguen/medios/applications/webmedios/controllers/admin.py", line 598, in <module>
  File "/home/gonguinguen/medios/gluon/globals.py", line 393, in <lambda>
    self._caller = lambda f: f()
  File "/home/gonguinguen/medios/applications/webmedios/controllers/admin.py", line 593, in test
    cf.zones.settings.always_use_https.patch(zone_id, data={"value": "on"})
AttributeError: '_add_with_auth' object has no attribute 'always_use_https'`

Notice the call I use is the same for both settings, as told by the official Cloudflare documentation. But the error happens only with "always_use_https".

I tried doing my self the call using python requests.
```
import requests
result = requests.patch('https://api.cloudflare.com/client/v4/zones/%s/settings/always_use_https' % 
    zone_id,
    data={'value': 'off'},
    headers={
        "Content-Type": "application/json",
        "X-Auth-Key": cloudflare_user_api_key,
        "X-Auth-Email": cloudflare_email
    }
)
```

But this returns the error code 6007 with the message "Malformed JSON in request body"

I've contacted Cloudflare support, and they told me that the call is right. 
Is this a bug in python-cloudflare library? Could it be related to requests module?

**UPDATE**
I've tried directly using the curl command and it works ok, so it isn't a bug in the Cloudflare API. Also, I've tried with several different zones, and the problem remains.

**Comment by mahtin** [comment]
@gonguinguen - Can you check your version number of your library:
```
$ cli4 --dump | grep always_use_https
/zones/settings/always_use_https
$

$ cli4 -V
Cloudflare library version: 1.8.1
$
```
The ``always_use_https`` API call is in the newest code; however, it was only added Sept/2017. Can you check the version of your code and maybe update it?

> commit 49f428e52ed0f1ea8845b7fa241d8044bea7d776
> Author: Martin Levy <martin@cloudflare.com>
> Date:   Tue Sep 12 00:16:18 2017 -0700
> 
>     1.7.5 release
> 
> commit dfe0afbec237c3f217f63ea8a92990eecb43a437
> Author: Martin Levy <martin@cloudflare.com>
> Date:   Mon Sep 11 08:30:00 2017 -0700
> 
>     added more API commands. Made some efficency edits to the python code 

I think an update would fix your initial code.

I have added https://github.com/cloudflare/python-cloudflare/blob/master/examples/example_always_use_https.py to GitHub. It's a direct example of how your request can be coded up. However, this brought up some interesting errors in the library with Python3 (3.5.2 and beyond). I think others have seen that. I need to review some other changes in ``requests()`` that affect JSON data.

BTW: your code snippet should work, you just need to change ``data=`` changed to ``json=`` in order for it to work. That said; just update the Cloudflare python library and you should be able to proceed. Please confirm.

**Comment by mahtin** [comment]
@gonguinguen - Once you upgrade; you will find this works for you:
```
$ cli4 /zones/:example.com/settings/always_use_https | jq -r .value
off
$ 
```
```
$ cli4 --patch value=on /zones/:example.com/settings/always_use_https | jq -r .value
on
$
```
```
$ cli4 /zones/:example.com/settings/always_use_https | jq -r .value
on
$
```
```
$ cli4 --patch value=off /zones/:example.com/settings/always_use_https | jq -r .value
off
$
```
```
$ cli4 /zones/:example.com/settings/always_use_https | jq -r .value
off
$
```

**Comment by gonguinguen** [comment]
@mahtin, thank you for your help. Yes, indeed, the library installed on my local machin was 1.5.1. As you suggested, I upgraded the library and it worked. Sorry I didn't realised before. Thanks again!
