### ISSUE TITLE
requirements.txt should specify the request version

### ISSUE THREAD

**Issue by brycehendrix** [cloudflare/python-cloudflare#48]
the `json` keyword on the session put & post methods requires requests>=2.4.2.  Old Ubuntu LTS versions ship with an older version which will cause an exception: ```CloudFlare.exceptions.CloudFlareAPIError: connection failed.```

**Comment by mahtin** [comment]
Noted. I will update the ``requirements.txt`` file.

**Comment by mahtin** [comment]
Done (but need to push to pip). See [fd6464e](https://github.com/cloudflare/python-cloudflare/commit/fd6464e15b91263f1ce395e4336b1c1fac542880#diff-b4ef698db8ca845e5845c4618278f29a).
