### ISSUE TITLE
Support the accounts endpoint

### ISSUE THREAD

**Issue by harmw** [cloudflare/python-cloudflare#50]
From: https://api.cloudflare.com/#organizations-properties

```
NOTE: This API is deprecated, please use equivalent /accounts API endpoints where possible. Account APIs provide a broader range of features, and are backwards-compatible to organization APIs.
```

```python
>>> cf.accounts.get()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'CloudFlare' object has no attribute 'accounts'
```

**Comment by jakubgs** [comment]
This is necessary for me too.
When I use `cf.user.audit_logs.get` I get only some of the audit logs.
What I need to do to get all audit logs is `cf.accounts.audit_logs.get`, but that does not exist. I worked around this by using `cf._base.call_with_auth`, but it is pretty annoying.

**Comment by mahtin** [comment]
Updated. Apologies for not responding earlier. Grab the latest at https://pypi.org/project/cloudflare/ via a `pip install --upgrade cloudflare` command.
