### ISSUE TITLE
zones.purge_cache.post() returns an incomplete response

### ISSUE THREAD

**Issue by gonguinguen** [cloudflare/python-cloudflare#52]
Accordingly to the oficial documentation [1], the API call to purge specific URLs of a zone should return a dictionary like this one:
```
{
  "success": true,
  "errors": [],
  "messages": [],
  "result": {
    "id": "9a7806061c88ada191ed06f989cc3dac"
  }
}
```

However, in the response object I'm receiving only the inner dictionary, the one that corresponds to the "result" key. I'm not receiving the parent dictionary with the other keys (success, errors, messages). Could this be a bug?

I'm using the version 2.1.0 of the library.
This is my code:

```
>>> r = cf.zones.purge_cache.post(
            my_zone_id, 
            data={'files': [
                'https://mydomain.com/image.jpg',
                'http://mydomain.com/otherimage.jpg']
            })
>>> print r
>>> {'id':'23fe45167b3dad00ae810cd597587da1'}
>>> print r.get('success')
>>> None
```

[1] https://api.cloudflare.com/#zone-purge-files-by-url

**Comment by dvershinin** [comment]
+1: Version 2.1.0-2.el7 (from EPEL on CentOS) - same bad behaviour.

**Comment by duffn** [comment]
Still experiencing the same with `cloudflare==2.3.0`.

**Comment by mahtin** [comment]
The library takes care of all the error conditions and raises them via a Python `exception` condition.  Hence only the data section is returned from all the calls. If the call is a success, then `"success": true, "errors": [], "messages": []` is always the case and only the contents of `results` are returned. This is part of the value-add that the library provides.

There's a raw mode for the library if you really want the extra data - which should only be needed if you want to page thru large responses. See the example folder for examples.
