### ISSUE TITLE
HTTPErrors should be caught and rethrown

### ISSUE THREAD

**Issue by davidfischer** [cloudflare/python-cloudflare#54]
I'm using the `cloudflare.zones.custom_hostnames.delete` endpoint and the endpoint throws a 500 error when a custom domain is in the state `crypto.custom_hostnames.search.select.unknown_state`. Instead, this should be caught and rethrown as a `CloudFlareError` so that all errors can be caught without specifying multiple exception classes.

    HTTPError: 500 Server Error: Internal Server Error for url: https://api.cloudflare.com/client/v4/zones/...

<img width="974" alt="screen shot 2018-08-06 at 11 49 24 am" src="https://user-images.githubusercontent.com/185043/43735162-d3bfe1a2-996e-11e8-97f0-9871bb56fefd.png">

**Comment by mahtin** [comment]
I should time this one out; however, I did test this today and I don't see any 500 errors (maybe this is fixed); however, I do see some issues with the `custom_hostnames` calls (mainly on the Cloudflare API side vs python side). I've opened a few internal tickets for this. In the meantime, I have some simple edits to allow command-line access to the `custom_hostnames` API cleanly. See below. 
```
$ cli4 /zones/:▮▮▮▮▮▮▮▮▮▮▮▮▮.com/custom_hostnames/
[]
$

$ cli4 --post method='txt' hostname='testing-123.▮▮▮▮▮▮▮▮▮▮▮▮▮.com' /zones/:▮▮▮▮▮▮▮▮▮▮▮▮▮.com/custom_hostnames
{
    "created_at": "2020-06-23T01:25:43.30935Z",
    "hostname": "testing-123.▮▮▮▮▮▮▮▮▮▮▮▮▮.com",
    "id": "64c993b7-a074-4f2a-82a5-5471dc96c0cd",
    "ssl": null
}
$

$ cli4 /zones/:▮▮▮▮▮▮▮▮▮▮▮▮▮.com/custom_hostnames/
[
    {
        "created_at": "2020-06-23T01:25:43.30935Z",
        "hostname": "testing-123.▮▮▮▮▮▮▮▮▮▮▮▮▮.com",
        "id": "64c993b7-a074-4f2a-82a5-5471dc96c0cd",
        "ssl": null
    }
]
$

$ cli4 --delete /zones/:▮▮▮▮▮▮▮▮▮▮▮▮▮.com/custom_hostnames/:testing-123.▮▮▮▮▮▮▮▮▮▮▮▮▮.com
{
    "created_at": "2020-06-23T01:25:43.30935Z",
    "id": "64c993b7-a074-4f2a-82a5-5471dc96c0cd",
    "ssl": null
}
$

$ cli4 /zones/:▮▮▮▮▮▮▮▮▮▮▮▮▮.com/custom_hostnames/
[]
$
```
Underlying Python calls also work cleanly.
