### ISSUE TITLE
Add method to get total requests made

### ISSUE THREAD

**Issue by Technerder** [cloudflare/python-cloudflare#61]
Add a method which returns the total number of requests that the site has received.

**Comment by mahtin** [comment]
This can be done with the existing [Cloudflare API](https://api.cloudflare.com/#zone-analytics-dashboard) using the `zone` `analytics` call. Here is the last 24 hours (1440 minutes) of stats:
```
$ cli4 continuous=false since=-1440 /zones/:${ZONE}/analytics/dashboard | jq '.totals.bandwidth|.all,.cached,.uncached'
109381
24685
84696
$
```
The same can be done via Python code. Grab the latest version of the code via https://pypi.org/project/cloudflare/

**Comment by mahtin** [comment]
According to https://api.cloudflare.com/#zone-analytics-properties ... 
```
Deprecation Warning
End of life Date: March 1, 2021
```
As this API above is now sunset'ed, you should use GraphQL to find this information. Please see https://developers.cloudflare.com/analytics/migration-guides/zone-analytics/
