### ISSUE TITLE
Unable to connect to logpush endoint via cli4

### ISSUE THREAD

**Issue by thatChadM** [cloudflare/python-cloudflare#71]
Trying to check and configure logpush jobs and was hoping to use cli4 to do it quickly, but it doesn't know the logpush endpoint.  It just returns the error /zones/:zoneid/logpush - not found.  Confirmed that it does work as expected via curl.

Tested using version 2.3.0

**Comment by thatChadM** [comment]
cli4 --get zones/:zoneid/logpush/jobs
cli4: /zones/:zoneid/logpush - not found

**Comment by mahtin** [comment]
Added via `2.4.4`. Please see https://pypi.org/project/cloudflare/ for an easy `pypi` install.
