### ISSUE TITLE
Support Enabling "Proxied" When POSTing a DNS Record

### ISSUE THREAD

**Issue by eldridgea** [cloudflare/python-cloudflare#73]
Currently when using `CloudFlare.CloudFlare.zones.dns_records.post()` including the argument `proxied` as docuemnted by the API returns `post() got an unexpected keyword argument 'proxied'`

**Comment by mahtin** [comment]
The `proxied` parameter for `dns_records` can be set to `true` or `false`. Here's some examples which show when it can be used.

Pardon the redacted zone name; but first set the zone name:
```
$ ZONE="██████████████████.com"
$
```

Creating a simple `A` record; notice the `proxiable` value is `true. This is key to understand.
```
$ cli4 --post name="example-0" type="A" content="52.52.1.1" /zones/:${ZONE}/dns_records
{
    ...
    "name": "example-0.██████████████████.com",
    "proxiable": true,
    "proxied": false,
    ...
}
$
```

If we do the same; but with a private IP space `A` record. Notice the `proxiable` value is `false`.
```
$ cli4 --post name="example-1" type="A" content="192.168.1.1" proxied=false /zones/:${ZONE}/dns_records
{
    ...
    "name": "example-1.██████████████████.com",
    "proxiable": false,
    "proxied": false,
    ...
}
$
```
This is becuase you can't proxy into a private IP space address.

We can see an error, if we try to set the `proxied` flag to `true`
```
$ cli4 --post name="example-2" type="A" content="192.168.1.1" proxied=true /zones/:${ZONE}/dns_records
cli4: /zones/:██████████████████.com/dns_records - 1004 DNS Validation Error
$
```
This is the error you maybe seeing.

Here is a successful use of the proxied` flag.
```
$ cli4 --post name="example-2" type="A" content="52.52.1.1" proxied=true /zones/:${ZONE}/dns_records
{   
    ...
    "name": "example-2.██████████████████.com",
    "proxiable": true,
    "proxied": true,
    ...
}
$
```
While these are written with the `cli4` command; it's the same affect as calling the Python library.

**Comment by incoming-th** [comment]
> The `proxied` parameter for `dns_records` can be set to `true` or `false`. Here's some examples which show when it can be used.
> 
> Pardon the redacted zone name; but first set the zone name:
> 
> ```
> $ ZONE="██████████████████.com"
> $
> ```
> 
> Creating a simple `A` record; notice the `proxiable` value is `true. This is key to understand.
> 
> ```
> $ cli4 --post name="example-0" type="A" content="52.52.1.1" /zones/:${ZONE}/dns_records
> {
>     ...
>     "name": "example-0.██████████████████.com",
>     "proxiable": true,
>     "proxied": false,
>     ...
> }
> $
> ```
> 
> If we do the same; but with a private IP space `A` record. Notice the `proxiable` value is `false`.
> 
> ```
> $ cli4 --post name="example-1" type="A" content="192.168.1.1" proxied=false /zones/:${ZONE}/dns_records
> {
>     ...
>     "name": "example-1.██████████████████.com",
>     "proxiable": false,
>     "proxied": false,
>     ...
> }
> $
> ```
> 
> This is becuase you can't proxy into a private IP space address.
> 
> We can see an error, if we try to set the `proxied` flag to `true`
> 
> ```
> $ cli4 --post name="example-2" type="A" content="192.168.1.1" proxied=true /zones/:${ZONE}/dns_records
> cli4: /zones/:██████████████████.com/dns_records - 1004 DNS Validation Error
> $
> ```
> 
> This is the error you maybe seeing.
> 
> Here is a successful use of the proxied` flag.
> 
> ```
> $ cli4 --post name="example-2" type="A" content="52.52.1.1" proxied=true /zones/:${ZONE}/dns_records
> {   
>     ...
>     "name": "example-2.██████████████████.com",
>     "proxiable": true,
>     "proxied": true,
>     ...
> }
> $
> ```
> 
> While these are written with the `cli4` command; it's the same affect as calling the Python library.

I just wasted 3 hours of testing because I tried to do just that from the example on the CF API "198.51.100.4" and "192.168.0.1":

```This is because you can't proxy into a private IP space address.```

Just this sentence saved me from my headaches, and after reading it I was like "Yeah make sense".

So thanks for it, but I believe this should have been helpful to got it from the doc or from the error message instead of the general "CloudFlare.exceptions.CloudFlareAPIError: DNS Validation Error"
