### ISSUE TITLE
Support API tokens

### ISSUE THREAD

**Issue by FranklinYu** [cloudflare/python-cloudflare#74]
API Tokens in beta are more secure than API Keys because they can be limited to a specific domain. See:

https://api.cloudflare.com/#getting-started-requests

**Comment by FranklinYu** [comment]
I think this is the related part:

https://github.com/cloudflare/python-cloudflare/blob/cf084ee22b454cbb50804c748ee969cab9c451a2/CloudFlare/cloudflare.py#L52-L100

I can probably try this myself, but how should I pass-in the API Token? We already have a parameter `token` for API Key.

**Comment by nijel** [comment]
How about considering `token` is an API Token when `email` is not set?

**Comment by nijel** [comment]
I've drafted solution in https://github.com/cloudflare/python-cloudflare/pull/76. It works for me, but it lacks documentation or tests.

**Comment by urc** [comment]
Could we get some action on this from Cloudflare, please? API tokens entered GA on August 30th, according to the blog post here;

https://blog.cloudflare.com/api-tokens-general-availability/

It's been three weeks since, but module as currently pulled from PyPi doesn't support them yet?

**Comment by Tugzrida** [comment]
@urc #76 is basically ready to go if you wanted to use it for testing. Just waiting on a merge at this point.

**Comment by FranklinYu** [comment]
@urc I think you need to directly contact them to ask what is blocking #76 from being merged, if you need so. They are not very active in this repository.
