### ISSUE TITLE
PATCH method for /zones/:identifier/dns_records

### ISSUE THREAD

**Issue by madchap** [cloudflare/python-cloudflare#81]
The PATCH method is currently not supported on this endpoint.

It would be very handy to turn on and off the 'Proxied' status of a DNS record.

**Comment by mahtin** [comment]
This does work. It seems it's missing from the README table. Please look at the [Cloudflare API](https://api.cloudflare.com/#dns-records-for-a-zone-patch-dns-record) page plus the example below:

Pardon the redacted zone name; but first set the zone name:
```
$ ZONE="██████████████████.com"
$
```

Create the DNS entry:
```
$ cli4 --post name="happy" type="TXT" content="Pharrell Williams - Happy" /zones/:${ZONE}/dns_records
{
    "content": "Pharrell Williams - Happy",
    ...
    "id": "bb91979d6a0b65591c99a4c648410c86",
    ...
    "name": "happy.████████████.com",
    "type": "TXT",
    "zone_id": "████████████████████████████████",
    "zone_name": "████████████.com"
}
$
```
Keep a track of it's `id` as you need it for the `PATCH` call.

```
$ dig +short TXT happy.${ZONE}
"Pharrell Williams - Happy"
$
```
So that works!

Now use `PATCH` to change the entry. Note how you need the `id` from above.
```
$ cli4 --patch name="happy" type="TXT" content="If It Makes You Happy - Sheryl Crow" /zones/:${ZONE}/dns_records/:bb91979d6a0b65591c99a4c648410c86
{
    "content": "If It Makes You Happy - Sheryl Crow",
    ...
    "id": "bb91979d6a0b65591c99a4c648410c86",
    ...
    "name": "happy.████████████.com",
    "type": "TXT",
    "zone_id": "████████████████████████████████",
    "zone_name": "████████████.com"
}
$
```

Test again:
```
$ dig +short TXT happy.${ZONE}
"If It Makes You Happy - Sheryl Crow"
$
```
Works!

Now clean up.
```
$ cli4 --delete /zones/:${ZONE}/dns_records/:bb91979d6a0b65591c99a4c648410c86
{
    "id": "bb91979d6a0b65591c99a4c648410c86"
}
$
```

The key is to rememberer that the `PATCH` call needs the DNS entries `id`.

**Comment by madchap** [comment]
So what I am getting in some other use-cases is this:

```
try:
        dns_records = cf.zones.dns_records.get(zone_id)
        for dns in dns_records:
        [...]
                if switch == "off":
                    print("Switching proxy off")
                    dns['proxied'] = False
                    print(json.dumps(dns, indent=4, sort_keys=True))
                    cf.zones.dns_records.patch(zone_id, data=dns)

    except CloudFlare.exceptions.CloudFlareAPIError as e:
        exit("DNS records call failed {}".format(e))
```

And it does return the following exception:

`DNS records call failed Method PATCH not available for that URI`

**Comment by mahtin** [comment]
The `patch` and `put` calls need a dns record `id`. Add the following lines:
```
    dns_record_id = dns['id']
```
Plus change the patch call to include the dns_record_id value ...
```
    cf.zones.dns_records.patch(zone_id, dns_record_id, data=dns)
```
This will match the call as described on the [Cloudflare API](https://api.cloudflare.com/#dns-records-for-a-zone-patch-dns-record) page. You will see that the `patch` call takes two `id`'s:
```
    PATCH zones/:zone_identifier/dns_records/:identifier
```
I hope that helps.

**Comment by mahtin** [comment]
Final point. There's an example that relates to this issue. See https://github.com/cloudflare/python-cloudflare/blob/master/examples/example_update_dynamic_dns.py#L77 for an example.

You can change this line that uses `put`:
```
    dns_record = cf.zones.dns_records.put(zone_id, dns_record_id, data=dns_record)
```
to a line using `patch`:
```
    dns_record = cf.zones.dns_records.patch(zone_id, dns_record_id, data=dns_record)
```
and they work exactly the same.

**Comment by madchap** [comment]
Most definitely help, and thanks to pointing me to my oversight. This works just fine. Cheers!
