### ISSUE TITLE
Python 3.8 warnings about "is with a literal"

### ISSUE THREAD

**Issue by aptalca** [cloudflare/python-cloudflare#83]
Python 3.8 is now displaying warnings when `is` is used with a literal.

Here are the warnings with 2.4.0:
```
/usr/lib/python3.8/site-packages/CloudFlare/cloudflare.py:839: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if email is '':
/usr/lib/python3.8/site-packages/CloudFlare/cloudflare.py:841: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if token is '':
/usr/lib/python3.8/site-packages/CloudFlare/cloudflare.py:843: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if certtoken is '':
```

See https://github.com/python/cpython/pull/9642 for more info

I am also submitting a PR with a fix.

Thanks

**Comment by mahtin** [comment]
Yeah - I found a bunch of these and pushed it as branch `fix-python-3.8` which is merged into `master` now and released as `2.4.1` on https://pypi.org/project/cloudflare/ (i.e. `pip3 install cloudflare`)
