### ISSUE TITLE
Does this support the new firewall rules (filters) and Cloudflare Access?

### ISSUE THREAD

**Issue by binaryfire** [cloudflare/python-cloudflare#87]
Hi guys,

Just wondering if the CLI supports firewall filters: https://developers.cloudflare.com/firewall/api/cf-firewall-rules/ and Cloudflare Access: https://api.cloudflare.com/#access-applications-list-access-applications ?

I couldn't see either listed in the readme.

Cheers

**Comment by mahtin** [comment]
@binaryfire - You can use this command to see what API calls the code contains. The README really provides an outline for the library usage. Hope this helps.
```
$ cli4 --dump | fgrep firewall
/accounts/firewall/access_rules/rules
/organizations/firewall/access_rules/rules
/user/firewall/access_rules/rules
/zones/firewall/access_rules/rules
/zones/firewall/lockdowns
/zones/firewall/rules
/zones/firewall/ua_rules
/zones/firewall/waf/overrides
/zones/firewall/waf/packages
/zones/firewall/waf/packages/groups
/zones/firewall/waf/packages/rules
$
```
