### ISSUE TITLE
Consistent issue with creating certain CNAMEs

### ISSUE THREAD

**Issue by armanos** [cloudflare/python-cloudflare#91]
I have a set of records that I am trying to create as CNAMEs in CloudFlare. Many of them are successful, however there are certain records that always fail to create and throw an error that is not terribly descriptive. I have found one reference to it in your codebase, but do not see why this error would be thrown for the same set of records everytime a call is attempted in trying to create them while other records succeed.

I have reached out to CloudFlare support, but they will not help since the error is coming from the Python module.

The error is: `You must specify identifier1`. The requests are being made with a token as opposed to a username and password. The call being made is:
```
CF_TOKEN = '<string of API token>'
CF_ZONE = '<string of zone ID>'
cf = CloudFlare.CloudFlare(token=CF_TOKEN)
new_cname = {'name': '<string name of CNAME record>',
                 'type': 'CNAME',
                 'content': '<string value of CNAME record>',}
try:
    cf.zones.dns_records.post(CF_ZONE, data=new_cname)
except CloudFlare.cloudflare.CloudFlareAPIError as e:
    print('There was a problem creating the DNS validation record for {} '.format('<string name of CNAME record>' + str(e))
```

An example of a failing `new_cname` dict is:
```
{'name': '_19b3a279aa2cb69039bd37c85c557c92.api.robinpowered.com.', 'type': 'CNAME', 'content': '_8d9d08826d5f4a56f590a47d674d5740.nhqijqilxf.acm-validations.aws.'}
```

Why would this record fail while others do not? Is there a better way to get a more useful error message?

**Comment by mahtin** [comment]
I coded this up and it works for both an email/token and an apitoken. I wonder if your value for CF_ZONE is correct in your situation. The `api.robinpowered.com` DNS entry isn't  a subdomain; it's just a DNS entry. Hence `_19b3a279aa2cb69039bd37c85c557c92.api.robinpowered.com` is also a DNS entry with it's zone being `robinpowered.com`. 

Please recheck. I'll put my code up in a second.

**Comment by mahtin** [comment]
My code to test this:
```
$ cat /tmp/issues91.py 
#!/usr/bin/env python

import sys
import CloudFlare

def issue91(host_name, zone_name, dns_type, dns_content):

    cf = CloudFlare.CloudFlare()

    dns_record = {
        'name': host_name,
        'type': dns_type,
        'content': dns_content
    }

    # print('%s . %s -> %s -> %s' % (host_name, zone_name, dns_type, dns_content))

    try:
        params = {'name': zone_name}
        zones = cf.zones.get(params=params)
    except CloudFlare.exceptions.CloudFlareAPIError as e:
        sys.exit('/zones.get: %s - %d %s - api call failed' % (zone_name, e, e))
    except Exception as e:
        sys.exit('/zones.get: %s - %d %s - api call failed' % (zone_name, e))

    if len(zones) == 0:
        sys.exit('/zones.get: %s - zone not found' % (zone_name))

    if len(zones) != 1:
        sys.exit('/zones.get: %s - api call returned %d items' % (zone_name, len(zones)))

    zone_name = zones[0]['name']
    zone_id = zones[0]['id']

    # print('%s -> %s' % (zone_name, zone_id))

    try:
        dns_record = cf.zones.dns_records.post(zone_id, data=dns_record)
    except CloudFlare.exceptions.CloudFlareAPIError as e:
        sys.exit('zones.dns_records.post: %s %s %s -%d %s - api call failed' % (host_name, dns_type, dns_content, e, e))
    print('zones.dns_records.post: %s %s %s - SUCCESS' % (host_name, dns_type, dns_content))

def main():

    try:
        host_name = sys.argv[1]
        zone_name = sys.argv[2]
        dns_type = sys.argv[3]
        dns_content = sys.argv[4]
    except IndexError:
        sys.exit('usage: issue91.py name zone type content')
    issue91(host_name, zone_name, dns_type, dns_content)
    sys.exit(0)

if __name__ == '__main__':
    main()
$
```
My results (the same with email/token and with apitoken:
```
$ /tmp/issues91.py api ⬛⬛⬛⬛⬛⬛⬛⬛.com CNAME robin-production-api-vpc-871829796.us-east-1.elb.amazonaws.com.
zones.dns_records.post: api CNAME robin-production-api-vpc-871829796.us-east-1.elb.amazonaws.com. - SUCCESS
$

$ /tmp/issues91.py _19b3a279aa2cb69039bd37c85c557c92.api ⬛⬛⬛⬛⬛⬛⬛⬛.com CNAME _8d9d08826d5f4a56f590a47d674d5740.nhqijqilxf.acm-validations.aws.
zones.dns_records.post: _19b3a279aa2cb69039bd37c85c557c92.api CNAME _8d9d08826d5f4a56f590a47d674d5740.nhqijqilxf.acm-validations.aws. - SUCCESS
$

$ dig +nocmd +noauth +nostat +nocomments api.⬛⬛⬛⬛⬛⬛⬛⬛.com
;api.⬛⬛⬛⬛⬛⬛⬛⬛.com.              IN      A
api.⬛⬛⬛⬛⬛⬛⬛⬛.com.       300     IN      CNAME   robin-production-api-vpc-871829796.us-east-1.elb.amazonaws.com.
robin-production-api-vpc-871829796.us-east-1.elb.amazonaws.com. 52 IN A 3.214.120.16
robin-production-api-vpc-871829796.us-east-1.elb.amazonaws.com. 52 IN A 54.82.174.97
robin-production-api-vpc-871829796.us-east-1.elb.amazonaws.com. 52 IN A 35.171.247.19
robin-production-api-vpc-871829796.us-east-1.elb.amazonaws.com. 52 IN A 34.224.77.95
$

$ dig +nocmd +noauth +nostat +nocomments _19b3a279aa2cb69039bd37c85c557c92.api.⬛⬛⬛⬛⬛⬛⬛⬛.com
;_19b3a279aa2cb69039bd37c85c557c92.api.⬛⬛⬛⬛⬛⬛⬛⬛.com.    IN A
_19b3a279aa2cb69039bd37c85c557c92.api.⬛⬛⬛⬛⬛⬛⬛⬛.com.     300 IN CNAME _8d9d08826d5f4a56f590a47d674d5740.nhqijqilxf.acm-validations.aws.
$
```

**Comment by armanos** [comment]
I am creating these entries in the robinpowered.com domain. The token has no issue creating other entires, such as:

`_7552f02db274f7f08139c107005f5915.assistant.preview.services.robinpowered.com.  CNAME _f0cbf56ddfb4f6049bfddafcbb29bce6.ltfvzjuylp.acm-validations.aws.`

**Comment by armanos** [comment]
I would also appreciate clarity on why you indicated that the api.robinpowered.com. entry is not a subdomain. Want to make sure I haven't missed something - all I am trying to do is create CNAMEs, not subdomains.

**Comment by armanos** [comment]
OK, I tried this request ad hoc (outside of the automation I wrote) and it was able to create the CNAME. Must be something in my code that is mangling the API token somewhere. Thanks for pushing me to do the right thing!

**Comment by mahtin** [comment]
OK. So to generate the `You must specify identifier1` error you would have to pass a `zone_id` of `None`. In your example, you clearly pass it a constant (which isn't `None`). That's confusing.

I have tested the code above with `token='⬛⬛⬛⬛⬛⬛⬛⬛'` and it works. I'm using version `2.6.3` of the code (see: https://pypi.org/project/cloudflare/).

**Comment by armanos** [comment]
I found it! A bug! In my own code nonetheless! I truly appreciate the speedy support:)

**Comment by armanos** [comment]
OK, while we are discussing... what is the right method to update an existing DNS record? The POST I am using (above) returns an error. Do I want a PATCH?

**Comment by armanos** [comment]
Clearly not...

```
CloudFlare.exceptions.CloudFlareAPIError: Method PATCH not available for that URI.
```

**Comment by mahtin** [comment]
Take a look at [example_update_dynamic_dns.py](https://github.com/cloudflare/python-cloudflare/blob/master/examples/example_update_dynamic_dns.py) and the PUT call:
```
        dns_record_id = dns_record['id']
        dns_record = {
            'name':dns_name,
            'type':ip_address_type,
            'content':ip_address,
            'proxied':proxied_state
        }
        try:
            dns_record = cf.zones.dns_records.put(zone_id, dns_record_id, data=dns_record)
        except CloudFlare.exceptions.CloudFlareAPIError as e:
            exit('/zones.dns_records.put %s - %d %s - api call failed' % (dns_name, e, e))
        print('UPDATED: %s %s -> %s' % (dns_name, old_ip_address, ip_address))
        updated = True
```
Note the need for the `dns_record_id` as the second parameter to the `zones.dns_records.put` call.

**Comment by armanos** [comment]
Many thanks! This module is great! Keep up the good work...
