### ISSUE TITLE
cli4.man not present in pypi release

### ISSUE THREAD

**Issue by FelixSchwarz** [cloudflare/python-cloudflare#94]
The man page seems to be explicitly excluded in commit 460d77bad7b255718e3986090b75458c6eef49a0 .

My problem: I'd like to use a signed release tarball. The pypi release is signed but does not contain the man page (which is packaged in Fedora). The github tarball is not signed.

**Comment by mahtin** [comment]
Yup
1) Somehow the man page has been forgotten. I'll fix that.
2) The upload to PyPI is signed; but you're right - no signing of GitHub tar balls.
... stay tuned!

**Comment by mahtin** [comment]
Please check `2.6.5` as it's now signed. See https://github.com/cloudflare/python-cloudflare/releases
If that's usable, I'll build a process to sign future releases.

**Comment by FelixSchwarz** [comment]
Signing github releases works for us as well. Probably it is a good idea to sign the zip file as well?

You might also want to check out [twine](https://pypi.org/project/twine/) instead of `setup.py sdist upload --sign`. As far as I understand that functionality is deprecated. Also twine is more flexible.

**Comment by mahtin** [comment]
Now `tar` and `zip` files signed. See https://github.com/cloudflare/python-cloudflare/releases/tag/2.7.1 for latest.
