### ISSUE TITLE
GraphQL Examples

### ISSUE THREAD

**Issue by lanec** [cloudflare/python-cloudflare#99]
I do not see any GraphQL examples in this repository. Is there any support for this API endpoint and this Python library?

**Comment by mahtin** [comment]
Yes. It will support it. I’ll dig up an example tomorrow.

**Comment by lanec** [comment]
Thank you for offering!

**Comment by mahtin** [comment]
@lanec - done! See https://github.com/cloudflare/python-cloudflare#cloudflare-graphql plus the examples folder for both python and shell script GraphQL examples.
